### ISSUE TITLE
Confusion sur les détails de mon bilan

### ISSUE THREAD

**Issue by DavidBruant** [datagir/nosgestesclimat-site#101]
Mon bilan est ici : https://ecolab.ademe.fr/apps/climat/fin?total=3795&details=s1.28a1.22l0.80t0.36n0.08d0.04

- Pour la nourriture, il y a écrit "1,2t", mais quand je vais sur le détail, je vois écris "2 846,4 kgCO2e" et je ne comprends pas la différence
- Pour la logement, il y a écrit "800kg", mais quand je vais sur le détail, je vois écris "2 545 kgCO2e / personnes" et je ne comprends pas la différence. Ma croyance, c'est que "2 545 kgCO2e", c'est sur le logement au total (ce qui donnerait ~800kg/personne vu qu'on est 3)

Un peu dans toutes les catégories, y'a des différences entre le graphique et ce que je vois quand je clique sur chaque section

**Comment by laem** [comment]
Merci pour le bug ! 
En fait comme tu l'as surement deviné, la page n'affiche que les informations contenues dans l'URL. 
Mais au clic sur les catégories, on repasse sur les valeurs par défaut des français. 
-> il faut qu'on indique clairement que les 2846kg de l'alimentation sont des valeurs par défaut. 
En lien avec #6
