### ISSUE TITLE
 🐛 Bouton "Continuer le sondage" qui ne fonctionne pas

### ISSUE THREAD

**Issue by nosgestesclimat** [datagir/nosgestesclimat-site#1017]
Firefox  112.0.2 windows 7
La touche "continuer le sondage" n'est pas active bien que j'ai attendu plus que nécessaire
> Depuis la page: `https://enquete--nosgestesclimat.netlify.app/simulateur/bilan`
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
@laem @bjlaa C'est bien un bouton présent sur l'enquête non ?

**Comment by bjlaa** [comment]
Je saurais pas te dire 😕 je laisse Maël te répondre

**Comment by laem** [comment]
Oui je confirme c'est sur le parcours d'enquête. Un bug rare apparemment. 

>  bien que j'ai attendu plus que nécessaire

C'est étrange, elle devient active non pas en attendant, mais en complétant le test. 

Ma meilleure hypothèse à ce stade c'est que l'utilisateur n'a pas complété le test ?

**Comment by laem** [comment]
Pour info, dans l'enquête, il y a eu l'essentiel (des milliers) d'utilisateurs à correctement cliquer sur ce bouton. Peut-être un bug très spécifique à un navigateur ?

**Comment by Clemog** [comment]
Oui effectivement, je sais pas si on le voit dans sentry. Le risque c'est que pour 100 personnes qui ont eu le cas, ce soit la seule à avoir envoyé un message 
Mais c'est clair que ça ne semble pas bloquant

**Comment by laem** [comment]
Je me permets de fermer.
