### ISSUE TITLE
Mettre en place la collecte de mails côté tech

### ISSUE THREAD

**Issue by lbranaa** [datagir/nosgestesclimat-site#1022]
Afin d'améliorer l'engagement sur Nos Gestes Climat et pour pouvoir aider l'utilisateur dans le temps, nous souhaitons pouvoir lui proposer de laisser son mail afin de pouvoir le recontacter dans le temps. 
Nous allons travailler côté design&produit pour définir la promesse et l'UX (ex : "rejoins la communauté Nos Gestes Climat pour que...") ; en parallèle, il faudrait mettre en place la collecte de mails côté tech.
Proposition --> utilisation de Sendinblue semble le plus simple / un compte partagé beta existe normalement (à creuser avec Florian).

**Comment by bjlaa** [comment]
- [ ] création d'une liste dans Sendinblue
- [ ] création / intégration du formulaire de collecte d'email en fin de questionnaire
- [ ] création d'une page de désinscription
