### ISSUE TITLE
Sentry `ChunkLoadError`

### ISSUE THREAD

**Issue by Clemog** [datagir/nosgestesclimat-site#1047]
Sentry remonte un nombre important d'évènements `ChunkLoadError` : j'espère que ce n'est pas cassant pour les utilisateurs ...

A investiguer je pense:

https://www.codemzy.com/blog/fix-chunkloaderror-react

**Comment by bjlaa** [comment]
À priori causé par l'absence de `webpackChunkName` au niveau des utilisations de `React.lazy` ce qui fait que webpack génère un id qui change parfois pour x ou y raison. Après un merge sur master, si c'est le cas certains utilisateurs ayant déjà accédé au site vont tenter de charger un chunk ayant changé de nom depuis et n'existant plus, ce qui génère l'erreur relevée par Sentry.

Protocole de correction proposé :
- [ ] Créer un premier commit vide ou avec une modif anodine, pusher et créer une PR afin que le build soit déployé en preview
- [ ] accéder à la preview et se promener dans l'app pour charger un maximum de chunks
- [ ] on revient dans le code : ajouter des `webpackChunkName` pour chaque `React.lazy`
- [ ] push et accéder à nouveau à l'app : vérifier que ça ne pète pas
