### ISSUE TITLE
🐛 Bug : l'ordre des catégories n'est plus fixé

### ISSUE THREAD

**Issue by JuliePouliquen** [datagir/nosgestesclimat-site#1048]
Lorsque l'on répond 0 à la première question sur le nombre de km en voiture / an, le simulateur bascule vers la catégorie Alimentation.

**Comment by Clemog** [comment]
@bjlaa j'ai l'impression que c'est suite à #1009 .. Je vois pas mal de changements dans `Conversation.tsx`

**Comment by bjlaa** [comment]
@Clemog Est-ce que l'ordre des catégories est défini dans `Conversation` ? Cette PR touche seulement aux useEffect qui déclenchent les évènements analytics, normalement ils ne devraient pas affecter l'ordre des catégories 🤔 je viens de vérifier je vois rien de curieux

**Comment by bjlaa** [comment]
Hmm bizarre 🤔 j'ai bien reproduis le bug en prod mais pas en local. Je suis retourné sur la prod, fait un hard refresh et je n'ai plus eu le problème. Est-ce que ce serait pas dû aux chunkloaderrors ?

**Comment by Clemog** [comment]
Merci pour la vérif !

**Comment by lbranaa** [comment]
Vous avez toujours le bug ? je n'arrive pas à le reproduire de mon côté
