### ISSUE TITLE
Retirer les mentions et logo Datagir du site

### ISSUE THREAD

**Issue by lbranaa** [datagir/nosgestesclimat-site#1056]
A la suite d'une réorganisation dans l'incubateur de l'ADEME pour plus de clarté, nous enlevons

- [ ]  les mentions de Datagir un peu partout sur le site
- [ ] le logo Datagir (notamment sur la homepage)

**Comment by dxb** [comment]
J'ai recensé 3 cas de figures :

le mail : datagir@ademe.fr qui devient contact@nosgestesclimat.fr
les liens vers le site datagir : https://datagir.ademe.fr/blog/budget-empreinte-carbone-c-est-quoi/
les mentions directes : "Copyright (c) 2022 Datagir" qui devient probablement "Copyright (c) 2022 Nos gestes climat"
