### ISSUE TITLE
Rajouter un tracker pour le taux d'abandon par question

### ISSUE THREAD

**Issue by lbranaa** [datagir/nosgestesclimat-site#1057]
Objectif : déterminer quelles questions génèrent du churn, détecter les potentiels d'amélioration
Pré-requis : que l'issue 1 URL par question (#1020) soit finalisée
--> Rajouter un tracker pour mesurer ce taux d'abandon

**Comment by EmileRolley** [comment]
Pas besoin de tracker spécifique, maintenant que #1020 est mergée il suffira de suivre dans Metabase le pourcentage de sortie associé aux différentes URLs.
