### ISSUE TITLE
Bug page stats "Intégration et iframes"

### ISSUE THREAD

**Issue by lbranaa** [datagir/nosgestesclimat-site#1061]
Bug lors de la récupation des données pour la partie "Intégrations et Iframes" sur la page stat du site

![Image](https://github.com/datagir/nosgestesclimat-site/assets/120486950/7f973535-4bb1-49f1-b3e3-9a183b241028)

**Comment by bjlaa** [comment]
Semble avoir été réglé tout seul :

https://nosgestesclimat.fr/stats

J'avance vite sur mes dernières issues, c'est cool 🤓
