### ISSUE TITLE
Bug quand on revient après avoir quitté le questionnaire / précédent

### ISSUE THREAD

**Issue by lbranaa** [datagir/nosgestesclimat-site#1063]
Le bug suivant a été remonté : quand on revient sur le site après avoir quitté le questionnaire, on ne retombe pas sur la question où on en était. Le bouton précédent bug aussi de temps en temps --> cela pourrait être lié

- [ ] Reproduire le bug
- [ ] Voir comment rendre plus robuste Conversation

A mettre en relation avec les changements en cours par Emile dans #1020

**Comment by dxb** [comment]
J'ai l'impression qu'avec le nouveau système d'url je n'arrive pas à reproduire le bug.

**Comment by bjlaa** [comment]
Le bug a muté ⚠ 

Suite d'actions pour reproduire le bug :
* démarrer un nouveau test ;
* répondre zéro à la première question ;
* copier l'URL de la question, fermer l'onglet et coller/accéder à l'URL ;
* répondre à la question.
Résultat : on est redirigé à la partie logement
Attendu : on reprend le fil de la complétion du test comme on l'avait commencée (on enchaine avec les autres questions transport)

**Comment by bjlaa** [comment]
Et pour info, quand on suit les actions que j'évoque plus haut et que l'on revient sur le site via l'URL de la page d'accueil, on reprend le test sur la catégorie Logement. À voir si c'est souhaitable ou non.

**Comment by lbranaa** [comment]
Je ferme l'issue et en crée une nouvelle pour le nouveau bug repéré (#1157)
