### ISSUE TITLE
Afficher de nouvelles métriques dans la page stats

### ISSUE THREAD

**Issue by lbranaa** [datagir/nosgestesclimat-site#1064]
L'objectif est d'améliorer la visualisation et donc le suivi de nos métriques clés.
Voici la liste des stats à rajouter dans la page stats : 

- [x] Simulations terminées : on les a en chiffre total, ce serait top d'avoir le petit graphique d'évolution (comme il y a pour les visites), pour suivre au fur et à mesure

- [ ] Nombre de visites uniques (bloqués par l'instance Matomo)
- [x] Nombre de visites totales qui arrivent sur la page d'accueil
- [ ] Nombre de personnes ayant accédé à la page "votre score" @lbranaa le total des vues de la page de fin ne peuvent pas être récupérées sur l'instance Matomo actuelle. Cette dernière implémente une limite de 500 URL suivies ; il se trouve que lorsqu'on termine notre simulation, un paramètres `details` est ajouté après `/fin`, ce paramètre contient les émissions pour chaque catégorie. Cela fait que chaque simulation crée une nouvelle URL, on a donc littéralement des millions d'URLs qui ne sont pas suivies. Ce problème est réglé sur l'instance Cloud Matomo que j'ai créé (cf https://github.com/datagir/nosgestesclimat-site/pull/1085). Je te propose de déjà mettre en prod l'ajout des stats disponibles et de créer une nouvelle carte avec les deux stats à ajouter 
- [x] Nombre de partages du lien

@margauxcoco @jeremiecook est-ce que vous en voyez des manquants ?

**Comment by margauxcoco** [comment]
Je me demande si on affiche aussi notre North Star metrics ? Et par ailleurs, peut être le nombre de sondages même si cela me semble moins important si besoin de prioriser ;)

**Comment by lbranaa** [comment]
Pour les North Star metrics et les données sondages, on va les afficher sur Metabase car ce ne sont pas des données qu'on a via Matomo

**Comment by bjlaa** [comment]
Si besoin c'est peut-être possible de récupérer les résultats via l'API Metabase, à confirmer !

**Comment by Clemog** [comment]
> Nombre de visites totales qui arrivent sur la page d'accueil

Je ne comprends pas cette indicateur ?

**Comment by lbranaa** [comment]
L'idée était de différencier le nombre de visiteurs qui arrivaient via la page d'accueil ou qui passaient pas d'autres pages directement (ex : directement sur le test)
