### ISSUE TITLE
Mieux préciser qu'il s'agit de l'impact sur mon empreinte carbone + rappeler total

### ISSUE THREAD

**Issue by martinregner** [datagir/nosgestesclimat-site#108]
- [ ] A la lecture, on peut comprendre qu'il s'agit de chiffres génériques moyens... Proposition pour préciser que c'est sur mon empreinte

![image](https://user-images.githubusercontent.com/46482115/95749701-495a0580-0c9c-11eb-9ed0-d409e39d5bfb.png)

- [ ] Garder affichée l'empreinte totale affichée (en haut ?) + barre de progression avant action / après action ? (éventuellement avec toutes les lignes pour voir celle qui bouge ?...)
![image](https://user-images.githubusercontent.com/46482115/95750253-2419c700-0c9d-11eb-9766-a610037e73b9.png)

**Comment by laem** [comment]
>  Proposition pour préciser que c'est sur mon empreinte

Sur la capture justement, c'est bien des valeurs par défaut, car tu n'as pas encore fait le test, d'où le gros bouton en haut.

On peut ajouter un texte en haut du style "en attendant que vous fassiez le test, voilà des estimations moyennes".

> Garder affichée l'empreinte totale affichée (en haut ?) + barre de progression avant action / après action ? (éventuellement avec toutes les lignes pour voir celle qui bouge ?...)
image

Tel quel le graphique prend trop de place pour qu'on l'affiche en haut. Par contre on peut en faire une barre horizontale ou juste mettre le total.

> barre de progression avant action / après action 

ça rejoint les réflexions qu'on a eu sur un "panier" d'actions simulées qui réduiraient l'empreinte. Je peux tenter un truc comme ça pour une v2

**Comment by Clemog** [comment]
Idée de comparaison des résultats avant/après identifiée, je ferme l'issue :)
