### ISSUE TITLE
Faire en sorte que l'ordre des cartes dans les mosaïque suive toujours celui de la `somme`

### ISSUE THREAD

**Issue by Clemog** [datagir/nosgestesclimat-site#1093]
Des différences entre les navigateurs semblent provoquer un affichage des mosaïques différent selon le navigateur..

- Chrome (qui ne suit pas l'ordre du modèle):

![](https://user-images.githubusercontent.com/55186402/242022858-b6bfd9cd-b942-4d24-8ec5-f9cc8a2fca7c.png)

- Firefox (qui suit l'ordre du modèle)

![](https://user-images.githubusercontent.com/1177762/242660238-be51c884-2e36-47a0-b8b7-d8a3f003d5d0.png)

**Comment by Clemog** [comment]
Tentative de modification du fichier `RuleInput.tsx`

Le bug a lieu ici :

```javascript
const selectedRules = mosaicDottedNames.map(
	([dottedName, questionRule]) => {
		console.log(dottedName)
		const parentRule = parentName(dottedName)
		return [rules[parentRule], questionRule]
	}
)
```


Impossible de comprendre pourquoi mais l'ordre en sortie du map n'est pas celui initial...

On a bien le bon ordre en affichant les dottedName passé à la fonction mais en sortie, l'ordre dans `selectedRules` est différent...

<img width="511" alt="image" src="https://github.com/datagir/nosgestesclimat-site/assets/55186402/7d4ac118-6f0b-4893-bf3d-7e25700a4875">

<img width="900" alt="image" src="https://github.com/datagir/nosgestesclimat-site/assets/55186402/c36e6547-0982-4367-9200-2923b6f358d4">


Si qqn a une idée ...

**Comment by EmileRolley** [comment]
(Il semblerait (d'après tes screens) que l'ordre est inversé) :/

Est-ce que ce n'est pas juste lié à la sémantique de JS qui ne préserve pas l'ordre dans `map` ?

**Comment by laem** [comment]
Dans le code qui génère l'ordre, je ne vois pas de pris en compte de l'ordre que tu sembles vouloir préserver, celui de la somme dans formule, ici : 

https://github.com/datagir/nosgestesclimat-site/blob/master/source/components/conversation/RuleInput.tsx#L76

La variable importante est définie ici et l'ordre de sa liste dépendra de l'organisation des règles dans le fichier yaml https://github.com/datagir/nosgestesclimat-site/blob/master/source/components/conversation/RuleInput.tsx#L76

Or, c'est un objet, pas une liste. Donc l'ordre de ses clefs est à considérer aléatoire.

Il faut donc à mon avis ajouter une étape de tri qui va la rendre conforme à la somme dans formule.

**Comment by Clemog** [comment]
@laem j'ai essayé d'appliquer ce que tu proposes mais je ne parviens pas à gérer le truc ..

https://github.com/datagir/nosgestesclimat-site/blob/db8128d7d3efa4f7f627ec8c348fe6d7b93ccfaf/source/components/conversation/RuleInput.tsx#L143-L151

**Comment by Clemog** [comment]
@laem normalement on est bons dans la cas ou la mosaique **est une somme**... Ce n'est pas toujours le cas ! Notamment pour l'énergie (#1912), je ne vois pas trop comment on va pourvoir gérer ça ! https://github.com/datagir/nosgestesclimat/issues/1912

**Comment by Clemog** [comment]
Est ce que t'es ok pour merger https://github.com/datagir/nosgestesclimat-site/pull/1116 malgré le "pb" des mosaiques qui ne sont pas des sommes ? Je peux faire une issue en parallèle
