### ISSUE TITLE
Volet alimentation : deux remarques

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat-site#126]
Bonjour,
dans le volet alimentation :
1 - les boutons +/- ne sont pas pratiques (des champs libres me semblent plus appropriés).
2 - vous ne permettez pas que certaines personnes ne prennent pas 14 repas par semaine (bouton validation grisé).

**Comment by Clemog** [comment]
Pour les boutons, j'ai expérimenté la possibilité d'intégrer un champs libre (sans supprimer les boutons +/-) mais je ne sais pas comment partager la modif du code correspondante :)
