### ISSUE TITLE
Partage d'une image du résultat de simulation

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#15]
Générer une image récap de la simulation en base64 à partager.

Utiliser la fonctionnalité de partage natif sur mobile, qui d'ailleurs sur Chrome permet de partager URL + image.

Pas de base de donnée pour stocker une URL de simulation pour l'instant.

**Comment by martinregner** [comment]
L'image de fin est top, et le partage via lien c'est parfait ! :)

Est-ce qu'ajouter au moins le 2 premiers postes d'émissions (ou tous ?) en + du total global (ex. picot + chiffre) ne permettrait pas de susciter + de curiosité au partage ("Et moi, est-ce que j'ai cette répartition aussi ?" "Ah mais lui c'est autant parce qu'il mange trop de viande !"...) ?
Ou 2 versions, pour les pudiques du détails, qui ne veulent pas trop dévoiler leur vie carbone ? ;)

Je rêve d'une interpélation d'un politique à l'autre sur Twitter "Et toi tu es à combien ?" ;p

**Comment by laem** [comment]
Oui, alors il faut encoder les résultats par catégorie dans l'URL, ça fera un peu long mais il faut tester

**Comment by laem** [comment]
Après réflexion, le mieux est d'utiliser les aperçus générés par la plupart des réseaux sociaux aujourd'hui, la balise <meta og:image>.
Sauf qu'on ne peut pas simplement utiliser html2canvas pour glisser une image binaire dans `content` car les réseaux sociaux s'attendent bien à une URL. 
Le plus simple me semble donc d'utiliser les fonctions netlify pour générer des images pour chaque URL de fin à la volée. 
N'a pas l'air très compliqué mais un peu de boulot quand même pour se remettre dans les fonctions netlify et y lancer un navigateur.

On peut regarder ces ressources : 
- https://medium.com/@danielsternlicht/capturing-dom-elements-screenshots-server-side-vs-client-side-approaches-6901c706c56f
- https://github.com/niklasvh/html2canvas
- https://dev.to/5t3ph/automated-social-sharing-images-with-puppeteer-11ty-and-netlify-22ln
