### ISSUE TITLE
Afficher la version du modèle utilisée

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#158]
Un bandeau en haut de l'écran qui affiche que l'interface de nosgestesclimat est en train d'utiliser un modèle qui n'est pas celui de l'ADEME.

Que ce soit pour une branche de développement, ou pour un modèle complètement différent, qui pourrait alors être nommé via un paramètre spécial du co2.json (par exemple : "campus Nantes").

**Comment by martinregner** [comment]
@laem vu les forks qui commencent à se multiplier (comme celui de Détour ou de [l'ESPC](https://10milliardsatable.wixsite.com/website/nos-gestes-climat) ...) il serait utile d'ajouter cette feature qui indique automatiquement que l'on est sur une version "non officielle" dès qu'il y a fork.

Le wording du bandeau qui s'ajoute ou mention en bas avant les logos pourrait être du genre : 
"Cet outil s'appuie sur Nos Gestes Climat dont le code est librement réutilisable. Cette déclinaison n'a pas été vérifiée par l'ADEME ni l'ABC."

**Comment by laem** [comment]
Je ferme, car on a carrément interdit l'utilisation du logo NGC sur les forks. Voir PERSONNALISATION.md
