### ISSUE TITLE
Text in .md files

### ISSUE THREAD

**Issue by Clemog** [datagir/nosgestesclimat-site#159]
Salut ! Il me semble que certaines portions textes qui devraient être en gras selon la syntaxe (FAQ.md, about.md) n'apparaissent pas en gras dans le navigateur (Safari et Chrome notamment).
Ex dans la FAQ :
\*\*Mais c’est là tout l’enjeu de la transition au sens large.\*\*

Sinon, je ne sais pas si il est possible de justifier les paragraphes facilement pour une question d'esthétique ?

**Comment by laem** [comment]
Ah oui, possible qu'on ait modifié le style de la balise <strong> à vérifier !

**Comment by laem** [comment]
> Sinon, je ne sais pas si il est possible de justifier les paragraphes facilement pour une question d'esthétique ?

A ma connaissance, jamais de justification de texte sur le Web. ça rend un texte plus difficile à lire. Mais je peux me tromper !

**Comment by laem** [comment]
ça me semble corrigé
