### ISSUE TITLE
Page budget

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#171]
Comme mon-entreprise.fr (piquer leur code), afficher le budget de la startup sur le site.

**Comment by hmartinez69** [comment]
Je veux bien m'occuper d'implémenter cette page, mais je n'ai pas de donnée sur le budget. Je peux récupérer cela quelque part ?

**Comment by mquandalle** [comment]
On peut maintenant référencer une page budget sur les fiches beta https://beta.gouv.fr/startups/datagir.html
Ça serait top que vous le fassiez pour insuffler le mouvement chez béta :)

**Comment by Clemog** [comment]
C'est fait ! :) https://datagir.ademe.fr/budget/
