### ISSUE TITLE
bug modifier les données

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat-site#185]
Bonjour,
Après avoir obtenu mon résultat, je clic sur modifier mes réponses. Je souhaite modifier la section "Logement". Je cilc sur la première question Logement, je la valide, mais la suivante est toujours la dernière question à laquelle j'avais répondu. En d'autres termes, pas moyen de refaire un bloc genre Logement après le résultat. Ca serait pratique. Je vais déménager bientôt et aurais bien aimé voir ce que ça fera sur mon bilan...
Merci en tout cas pour cet outil vraiment super !

**Comment by laem** [comment]
Je rouvre ici car c'est bien un problème d'UX pas urgent mais bien présent.

**Comment by laem** [comment]
Je me permets de ferme ça, la page profil,qui sera améliorée, s'en charge déjà pas tropmal
