### ISSUE TITLE
Naviguation dans "compréhension du calcul"

### ISSUE THREAD

**Issue by Benjamin-Boisserie-ABC** [datagir/nosgestesclimat-site#23]
Une fois cliqué sur "compréhension du calcul" puis sur une rubrique "Logement", "Numérique", etc. on ne peut plus revenir aux choix des sous rubriques

Ex : je clique sur "Numérique" je peux naviguer à l'intérieure de cette rubrique mais je ne peux pas "remonter" d'un cran et aller dans la partie "logement"

**Comment by laem** [comment]
@Benjamin-Boisserie-ABC c'est vrai qu'il n'y a pas de bouton retour ou de "breadcrumbs" (du style : bilan > numérique > tablette), mais la navigation est possible avec le bouton retour du navigateur. 

A tester avec davantage d'utilisateurs, pour voir si ce réflexe d'utiliser le bouton retour du navigateur n'est pas présent pour la majorité.

**Comment by laem** [comment]
Je pense que ce problème est réglé maintenant qu'on peut cliquer sur les catégories du graphique, il fait office de menu. 
ça te convient @Benjamin-Boisserie-ABC ?
