### ISSUE TITLE
Suite NGC conférence

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#230]
## Résoudre quelques bugs

- [ ] mettre le bouton conférence sur la page d'accueil ? 
- [x] bug sur "partager ce lien", undefined
- [ ] bug quand on ouvre la simulation dans un nouvel onglet : il faut la stocker
- [ ] étudier le fait d'utiliser le serveur de signaling yjs sur heroku, ou notre serveur
- [x] un `undefined` sur le graphe
- [ ] attribution des noms automatiques de fruit : s'assurer qu'ils sont uniques et les combiner
- [x] ajouter des graphes : lesquels ?
- [x] fixer les couleurs dans le navigateur
- [x] donner aux barres de moyenne la couleur des utilisateurs
- [x] vérifier le fonctionnement des barres de moyenne, on dirait que certaines peuvent ne pas s'afficher
- [ ] https://github.com/datagir/nosgestesclimat-site/issues/236
- [ ] afficher la possibilité de conférence sur une nouvelle page "partage", voir #232 

## Tester avec un premier groupe, par exemple betagouv

@fjg

**Comment by martinregner** [comment]
>  - [ ] mettre le bouton conférence sur la page d'accueil ?

Peut-être pas en tant que tel mais dans un bouton "**Diffuser Nos Gestes Climat**" ou approchant ?

Pas mal de prospects passent à côté du script pour intégrer NGC en iframe, qu'ils ne pensent pas à aller chercher dans "A propos". Ca vaudrait le coup de le mettre aussi dans cette nouvelle section.

>  ## Tester avec un premier groupe, par exemple betagouv
Dans nos échanges avec @Clem-mrtn, on a quelques volontaires pour tester.

**Je me permets d'ajouter :**

- [ ]  Ajouter les moyennes sur les 5 catégories (toutes sauf "Services publics" où le suspense est modéré ^^)

**Comment by laem** [comment]
> Peut-être pas en tant que tel mais dans un bouton "Diffuser Nos Gestes Climat" ou approchant ?

Non l'idée de cette proposition (qu'on a eue avec @fjg conjointement) c'était de permettre à quelqu'un de faire sa simulation avec des amis. Donc *avant* de la lancer, il faut qu'il sache cette possibilité. Mais bon, à tester, c'est peut-être un cas d'usage pas si courant. Et on peut **au moins** le mettre sur une page de diffusion comme tu dis :)

**Comment by martinregner** [comment]
> Peut-être pas en tant que tel mais dans un bouton "Diffuser Nos Gestes Climat" ou approchant ?

(Pour ne pas poluer ce ticket avec ça j'en ai fait un autre https://github.com/datagir/nosgestesclimat-site/issues/232 )

**Comment by laem** [comment]
Je ferme car rappatrié sur la PR #222
