### ISSUE TITLE
Liens du bas sur l'écran d'accueil

### ISSUE THREAD

**Issue by martinregner** [datagir/nosgestesclimat-site#232]
Proposition d'évolution des liens en bas de la page d'accueil pour mieux mettre en visibilité de nouvelles fonctionnalités / augmenter la diffusion sous d'autres formes que le partage de résultat :

- **A propos** ; y intégrer :
  - Nouveautés
  - Vie privée
- **Documentation**
- **Version conférence**
- **Intégrer Nos Gestes Climat** ou **Diffuser Nos Gestes Climat**
  - L'outil est librement diffusable ...
  - Script
  - Découvrez les principaux réutilisateurs sur https://datagir.ademe.fr/apps/nos-gestes-climat/

**Comment by Clem-mrtn** [comment]
Je valide ! 
Suite à quelques retours utilisateurs on s'est un peu rendu compte que le script pour intégration était pas évident à trouver pour ceux qui souhaiter l'intégrer. 

Du coup pq ne pas reprendre les codes Partage, Nous Contacter, Intégrer etc. des autres simulateurs (les boutons sur le côté ?)

**Comment by laem** [comment]
Voir  #240 aussi

**Comment by laem** [comment]
@Clem-mrtn j'ai repris le style du bouton partager de monimpacttransport

L'intégration du menu sur le côté, on pourra le faire dans un second temps, mais de toutes façon sur mobile c'est pas possible (trop peu de place), et pour l'instant je préfère ne pas trop passer de temps sur les particularités du mode bureau.
