### ISSUE TITLE
Vie privée

### ISSUE THREAD

**Issue by martinregner** [datagir/nosgestesclimat-site#233]
En fin de section on est renvoyé vers https://datagir.ademe.fr/vieprivee mais qui n'existe plus.

La gestion des cookies est-elle encore possible sur la nouvelle version du site @florianpanchout ?

**Comment by laem** [comment]
Ah bien vu ! Maintenant qu'on a une propriété pour chaque site, il faudra que l'utilisateur désactive le tracking pour chaque site, et qu'on mette une page sur chaque site :/

**Comment by laem** [comment]
Ah non, je découvre que matomo propose de désactiver pour tout stats.data.gouv.fr. J'intègre ça.

```<iframe
        style="border: 0; height: 200px; width: 600px;"
        src="https://stats.data.gouv.fr/index.php?module=CoreAdminHome&action=optOut&language=fr&backgroundColor=&fontColor=&fontSize=&fontFamily="
        ></iframe>```

**Comment by martinregner** [comment]
A intégrer aussi sur le site datagir ? (c'est en effet ce type d'iframe qu'il y avait avant pour la vie privée)

**Comment by laem** [comment]
> A intégrer aussi sur le site datagir ? (c'est en effet ce type d'iframe qu'il y avait avant pour la vie privée)

Sur chaque domaine datagir je pense.

**Comment by martinregner** [comment]
pourquoi pas avoir une page sur le site datagir, et que chaque simulateur pointe dessus ?
Si j'ai bien compris ça désactive pour tous les sites suivis par matomo ou aucun
