### ISSUE TITLE
Integration NosGestCliamts dans application. 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat-site#240]
Bonjour, 

Nous souhaitons intégrer NosGestsClimat dans une application web puis utiliser les données pour les afficher dans des dashboard. Cependant nous ne savons pas ou ni comment récupérer les données des différents formulaires. 

Auriez vous des conseils pour pouvoir accéder au résultat de l’utilisateur sur le total CO2e/an et des différentes catégories (Transport, Alimentation, Logement, Divers, Services Publics, Numérique). 

Merci pour votre aide, bien cordialement. 
--
Etienne Douillard. 

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Bonjour, pour l'instant la seule possibilité, c'est de forker ce dépot (nosgestesclimat-site) pour ajouter votre brique de communication serveur, qui enregistre les données. Nous ne le faisons pas.

Par contre, on peut aussi discuter d'un mode d'intégration iframe où vous passez au simulateur une URL, que l'on va taper en fin de simulation selon un schéma dont nous aurons parlé à l'avance. Est-ce que ça vous intéresse ? 


Soit 


et merci pour votre message, nous allons l'inscrire dans la documentation :)

**Comment by laem** [comment]
Un utilisateur a plus ou moins implémenté ce besoin :) 

Je ferme au profit du travail en cours : https://github.com/datagir/nosgestesclimat-site/pull/298
