### ISSUE TITLE
Bug affichage bouton Partager 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/nosgestesclimat-site#244]
Sur Chrome bug d'affichage du bouton PARTAGER 

![image](https://user-images.githubusercontent.com/76995768/117109799-7deef500-ad85-11eb-9ed1-e61bf3cb88c2.png)

![image](https://user-images.githubusercontent.com/76995768/117109932-b2fb4780-ad85-11eb-83ee-6320bbce275d.png)

+ Peut-être envisager également de faire un toolkit pour ceux qui ne comprendraient pas le sigle ?

**Comment by laem** [comment]
Bien vu :)
