### ISSUE TITLE
"diffuser" plutôt que "partenaires" sur la page d'accueil

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/nosgestesclimat-site#245]
Sur la "page d'accueil", je clarifierais encore davantage le lien qui redirige vers le script.
Je suis pas certaine que **"Partenaires"** ce soit très parlant pour ceux qui cherchent à intégrer le simulateur (on se dit pas forcément que c'est dans cette catégorie qu'on trouvera le script)

Plusieurs reformulations possibles :  
- **Réutilisateurs** 
-  **Intégration**  
- et je remplacerais le picto 💻 

Ou alors pour être encore plus explicite, on peut se mettre un petit wording avec redirection en dessous des trois logos ["Vous souhaitez intégrer ce simulateur à votre site ou application mobile ?" ](https://nosgestesclimat.fr/partenaires)

**Comment by Clem-mrtn** [comment]
Nouvelle suggestion après concertation & réflexion : changer "Partenaires" par **"💻 Diffuser"**

**Comment by martinregner** [comment]
En effet @laem on trouve que ce sera plus clair (et nous détachera de la dimension de "partenariat" qui est plus poussée que ce que l'on recherche)

**Comment by laem** [comment]
ça marche, j'avais mis "partenaires" dans l'idée qu'il y avait beaucoup de façons différentes d'intégrer nosgestesclimat, dont des façons qu'on n'a pas encore bien imaginé.
Je trouvais que "diffuser" est un peu trop restrictif, car ça ne prend pas en compte l'intérêt de la personne pour son organisation, mais essayons ! 

J'aurai pas le temps de faire ça aujourd'hui, il faut faire la modif à plusieurs endroits : https://github.com/datagir/nosgestesclimat-site/search?q=partenaires

**Comment by laem** [comment]
J'ai mis "diffuser" et l'icône 📤

**Comment by Clem-mrtn** [comment]
Top !
