### ISSUE TITLE
Page résultat : Rajouter du wording pour inciter à l'intégration 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/nosgestesclimat-site#246]
![image](https://user-images.githubusercontent.com/76995768/117117271-a5e35600-ad8f-11eb-9183-388c5ec0af63.png)

Sur cette page résultat on a déjà le partage : ça c'est pour le Citoyen.
Mais à mon sens il manque une partie "biz dev". Je rajouterais bien : 
**" Vous souhaitez intégrer ce simulateur ? Copiez ce code puis ajoutez-le où vous souhaitez qu'il s'affiche sur votre site web _<script id="nosgestesclimat" src="https://nosgestesclimat.fr/iframe.js"></script_
Vous souhaitez réutiliser les données brutes ou obtenir de l'aide pour un projet ? Contactez nous à datagir@ademe.fr pour bénéficier de notre expertise et accompagnement."**

**Comment by laem** [comment]
Je suis pas convaincu de l'intérêt de mettre un texte pour les intégrateurs potentiels sur cette page : il y a maintenant plus de 2000 visiteurs par jour, c'est un site qui devient grand public, sachant que très peu de gens sont responsables d'un site où une intégration est possible.

Les visiteurs risqueraient d'être perturbés par ce message technique / partenarial.
