### ISSUE TITLE
Retour après test du mode conférence (béta)

### ISSUE THREAD

**Issue by Benjamin-Boisserie-ABC** [datagir/nosgestesclimat-site#247]
Je mets ça là car je ne sais pas ou le mettre.

J'ai utilisé la version beta du mode conférence (à 4 en interne à l'ABC) et j'ai qq retours : 

**Fonctionnement**
Tout le monde m'a fait le même retour en disant que le bouton "Votre simulation" n'est pas facilement trouvable. Je pense que la section "Comment ça marche ?" pourrait être mise en premier

**Tableau de bord**
1. Ok pour la moyenne totale 
2. C'est intéressant d'afficher l'ensemble des résultats sur une seule et même échelle. Je pense que ça serait bien que l'échelle soit graduée (de 2t en 2t). J'ai eu du mal à comprendre ce que c'était en première lecture et c'est en faisant une simulation climaticide (22 t) que j'ai compris que le but était de représenter sur une même échelle les résultats. Je pense qu'un code couleur plus prononcé serait plus judicieux. Voila ce que je voyais : 
![image](https://user-images.githubusercontent.com/66410914/117483002-76864200-af65-11eb-86db-8b514340bd09.png)
Sans avoir à demander le nom ou pourrait demander à la personne qui fait la simulation de renseigner ces initiales afin de pouvoir localiser les participants plus facilement sur l'échelle
3. Vraiment pas facile à comprendre en 1ère lecture mais je pense que le but est ici aussi de présenter l'ensemble des résultats des participants mais par poste. C'est bien ça ? Même remarque donc sur la nécessité d'une échelle et d'un code couleur plus prononcé. A voir si ici aussi on pourrait utiliser les initiales. On pourrait aussi utiliser des formes si le code couleur ne couvre pas le nombre de participants.
4. Ce tableau de bord est gérable pour un petit groupe (< 20 pers.). Il faudra réfléchir à des tableaux de bord simplifiés pour des plus grande simulation. 

**Animation**
On pourrait mettre en forme des graphes pour faciliter la restitution/présentation aux participants 
a. On pourrait classer les postes majoritaires d'émissions parmi ceux qui font le test. Cela permettrait de dégager des profils (je caricature mais urbain c'est les transports avec l'avion, rural c'est l'alimentation avec la viande). Ex excel 
![image](https://user-images.githubusercontent.com/66410914/117484272-28723e00-af67-11eb-9646-6b3224da1219.png)

b.On pourrait afficher sur un graphe l'ensemble des empreintes (quand l'échantillon de test n'est pas trop large bien sûre) avec un trait à 2t et un à 11t. Ex 
![image](https://user-images.githubusercontent.com/66410914/117484537-7d15b900-af67-11eb-9c45-adf3bf432515.png)

Voila pour un premier retour

**Comment by laem** [comment]
> Ce tableau de bord est gérable pour un petit groupe (< 20 pers.). Il faudra réfléchir à des tableaux de bord simplifiés pour des plus grande simulation.

Oui complètement, il faudra qu'on mette en place une infrastructure de test pour simuler des grosses simulations.

**Comment by laem** [comment]
J'ai intégré les points restants sur  #252
