### ISSUE TITLE
Améliorations possibles du mode groupe

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#252]
- [x] afficher une échelle pour les catégories / les moyennes
- [x] afficher les couleurs du graphe de simu pour les catégories <- non, les utilisateurs sont déjà en couleur
- [ ] mettre en place une petite infra qui simule x utilisateurs dans l'interface
- [x]  une fonctionnalité "laser" ou "projecteur" : l'utilisateur peut rester appuyer sur un bouton qui met en évidence son empreinte à tout le monde.
- [x] améliorer le parcours : titre conférence beta seulement au-début, pas après en régime de croisière; tuto tout en haut puis "j'ai compris"
- [ ]  bug quand on ouvre la simulation dans un nouvel onglet : il faut la stocker. Pas prioritaire : on peut toujours retaper le lien de conférence partagé.
- [ ] laisser les utilisateurs se renommer pour donner leur identité, leurs initiales ou le pseudo qu'ils veulent <- pose des problèmes de confidentialité, veut-on les aborder ? 
- [x] mettre le bouton conférence sur la page d'accueil. "Faire le test à plusieurs"
- [x] proposer des noms de conf aléatoires cool (exemple, des glaciers + un nom de réunion genre "conférence", "réunion", "rassemblement", etc.) 
- [x] animer le chiffre de la barre avec [ça](https://codesandbox.io/s/framer-motion-counter-wfh4j?file=/src/App.js) <- pas possible, le nombre n'a qu'un chiffré, ça rend pas.
- [x] varier les possibilités de nommage avec des adjectifs neutres [ici](http://www.occe.coop/~ad86/IMG/pdf_adjectifs.pdf)

**Comment by martinregner** [comment]
- [ ] https://nosgestesclimat.fr/conf%C3%A9rence charge une page blanche ; à rediriger vers /groupe ?
- [ ] Sur le point 2 : retirer le texte prévenant de la limitation sur conférence lorsque l'on sélectionne sondage et le remplacer par un texte prévenant qu'à l'issue des 2 semaines TOUT est supprimé (non ?).
![image](https://user-images.githubusercontent.com/46482115/157194454-7887ac03-b310-4c28-a7e9-e0fa388294e8.png)
- [ ] Sur la durée en 4, je trouve la durée de 2 semaines très courte ; l'idéal serait de pouvoir choisir entre par ex. 2-4-6 (tant pis pour les évolutions de modèle entre temps) ; dans tous les cas il faut prévenir à nouveau ici qu'à l'issue de ces 2 semaines tout est supprimé et qu'il faut donc télécharger les résultats avant

**Comment by Clemog** [comment]
@Clem-mrtn je ne retrouve pas l'issue dans laquelle on en parlait ..?

- [ ] Avoir la possibilité d'appliquer une action à tous les utilisateurs (à l'image d'une action que tout le monde adopterait)
- [ ] Sauvegarder les résultats après choix d'actions (pour le mode sondage) 
> Je voulais savoir aussi, j’ai fait un test de nos gestes climat à plusieurs et je me demandais s’il était possible de connaitre les résultats agrégés des bilans carbone après avoir identifié des pistes de réductions ? Car l’agrégation se fait sur les bilans carbone initiaux mais je n’ai pas vu pour avoir cette donnée pour les bilans après réductions ?

**Comment by jeannelf** [comment]
obsolete avec mode orga en préparation
