### ISSUE TITLE
Problème de connection mode conférence

### ISSUE THREAD

**Issue by fjg** [datagir/nosgestesclimat-site#255]
Une personne à qui j'ai diffusé NGC conférence m'a fait ce retour :

* elle avait déjà fait une simulation en locale pour elle et pour tester

Le jour de la conférence elle a réutilisé le même lien qu'elle a diffusé aux autres participants. Tous les participants voyaient bien les autres et voyaient la simulation mais pas elle. Elle est resté sa simulation fixe.

Lien vers la conf : https://conf--nosgestesclimat.netlify.app/conf%C3%A9rence/lilo

Retour : La moyenne du groupe à 2,7 tonnes ça ressemble plutôt à mon empreinte perso quand on avait fait la simulation ensemble en avril. Leur moyenne a eux était à 7,2 tonnes je crois.

Capture d'écran
![photo_2021-05-26_10-04-56](https://user-images.githubusercontent.com/91435/119624946-3219f380-bdf9-11eb-9efb-766443191868.jpg)

**Comment by laem** [comment]
> elle avait déjà fait une simulation en locale pour elle et pour tester

Alors, je viens de tester, je ne pense pas que le problème vienne de là.

Vue la capture d'écran, il d'agit d'un problème de communication avec le serveur / les autres participants en P2P.

Tu as plus d'infos sur le navigateur utilisé / la version / le réseau ? 
Firefox / ? / ?
