### ISSUE TITLE
Mode Conférence : Homepage

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/nosgestesclimat-site#259]
Afin de guider un peu mieux l'utilisateur dans ce nouveau mode je mettrais plutôt le paragraphe "Comment çà marche" directement sur la Home Page du mode conférence , juste en dessous du champs " Saisissez un nom de salle" 

![image](https://user-images.githubusercontent.com/76995768/120304856-72cdad00-c2d0-11eb-8a62-24b909b35d51.png)

![image](https://user-images.githubusercontent.com/76995768/120304893-7b25e800-c2d0-11eb-9a5a-50d479db1263.png)

**Comment by martinregner** [comment]
je +1 :) On limitera p-e le nombre de salles "test" par des personnes qui veulent savoir un peu mieux de quoi il s'agit avant de se lancer
Le comment ça marche peut être laissé dans l'écran suivant @laem , avec le bouton pour cliquer sur "votre simulation"

Pour cette page, je propose ainsi d'adapter le texte en : 

## 🏟️ Conférence
1. Choisissez un nom de salle pour lancer ou rejoindre une conférence : `choisissez un nom de salle`
2. Partagez **ce lien** avec vos amis, collègues, etc. : `url complet en nosgestesclimat.fr/conférence/...`
3. Au moment convenu, ouvrez tous **ce lien** en même temps et commencez vos simulations : les résultats pour chaque catégorie (alimentation, transport, logement ...) s'affichent progressivement pour l'ensemble du groupe

Vous êtes déjà prêt à démarrer ? `Bouton c'est parti`

## Et mes données ?
...
