### ISSUE TITLE
Afficher une décimale pour le total de la simulation

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#263]
Quand on est au-dessus de 10 tonnes, on n'affiche plus que l'unité, pas la décimale. 
C'est dommage notamment pour voir le chiffre bouger au fil des questions. Par exemple pour l'immobilier.

**Comment by Clemog** [comment]
Je suis d'accord, c'est une correction assez rapide, je pense que ça peut être intéressant !
