### ISSUE TITLE
Contrôle de l'ordre des questions

### ISSUE THREAD

**Issue by Clemog** [datagir/nosgestesclimat-site#264]
Pb aujourd'hui : la génération automatique du questionnaire ne colle pas avec le design attendu des questions suivies

Une possibilité de contrôle de l'ordre des questions (sous-catégorie) à l'intérieur des catégories permettrait de résoudre certains bugs relatifs aux conditions d'applicabilité des questions. 

Exemple dans la déclinaison universitaire : https://github.com/SustainabilityCN/nosgestesclimat-site-ECN (branche tentative-rebase)
- La mosaïque des choix des moyens de transport domicile-travail n'apparaît pas après les premières questions sur les trajets domicile-travail lorsque la valeur par défaut est différente de 0 pour le voiture (par exemple). On a alors les questions relatives à la voiture avant la mosaique de choix des transports. J'ai donc remarqué ici que les valeurs par défaut prennent le dessus sur les conditions "applicables si".

- Dans la catégorie "Transport", la question “avez vous effectué une mobilité” devrait être suivie par “quel moyen de transport pour cette mobilité”, ce qui n'est pas le cas pour le moment.

Une solution proposée était de déplacer les sous catégories concernées au premier niveau d'espace nom mais je n'ai pas réussi.

**Comment by laem** [comment]
Je fais le lien avec l'issue qui décrit une partie de ce problème, https://github.com/betagouv/publicodes/issues/30
Et celle-ci, plus récente et meta sur le sujet : https://github.com/betagouv/publicodes/issues/33
