### ISSUE TITLE
Valeurs par défaut mosaïques

### ISSUE THREAD

**Issue by Clemog** [datagir/nosgestesclimat-site#265]
Dans le cas ou l'on souhaite définir plusieurs valeurs par défaut selon un critère, (exemple dans la déclinaison universitaire avec plusieurs valeurs par défaut selon le profil de l'utilisateur défini à la première question), la mosaïque ne "comprend" pas ce mécanisme puisqu'elle attend une valeur j'ai l'impression. Pour les questions classiques, le mécanisme "variation" dans la valeur "par défaut" fonctionne à priori. 
Je n'ai pas réussi à trouver la solution, c'est peut-être pas grand chose 😉

**Comment by laem** [comment]
C'est probablement que le composant Mosaïque va récupérer la valeur par défaut sauvagement, plutôt que d'appeler engine.evaluate() dessus.

C'est ici je pense : https://github.com/datagir/nosgestesclimat-site/blob/master/source/components/conversation/select/SelectDevices.tsx#L39

On devrait évaluer cette valeur.

**Comment by Clemog** [comment]
En fait je me rends compte que le mécanisme fonctionne pour les mosaïques qui n'ont pas de compteur. Il me semble que l'erreur vient du "chipsCount" mais je n'arrive à bien comprendre comment modifier le code en appelant engine.evaluate(..).  https://github.com/datagir/nosgestesclimat-site/blob/master/source/components/conversation/select/SelectWeeklyDiet.js

**Comment by laem** [comment]
Ah oui, cette fonction "chipsCount" semble bancale et devrait faire appel au moteur. 

Si je comprends bien, c'est donc une valeur de type "compte" dont la valeur par défaut est calculée plutôt que simplement saisie en dur, c'est bien cela ? 

Tu as le lien vers la ligne YAML correspondante ?

**Comment by Clemog** [comment]
C'est bien une valeur de type "compte" dont la valeur par défaut devrait être évaluée en faisant appel au moteur. Yes c'est ici ;) : 
https://github.com/datagir/nosgestesclimat-site/blob/5c5f8e9a136d823ccf1a22751bf4efff168f7b07/source/components/conversation/select/SelectWeeklyDiet.js#L24

**Comment by laem** [comment]
@Clemog je crois qu'on a corrigé ça non :) ?

**Comment by Clemog** [comment]
Yes ! Ici : [88a50bacac0d4d58b8e5e7c96701153ad45e9474](https://github.com/datagir/nosgestesclimat-site/commit/88a50bacac0d4d58b8e5e7c96701153ad45e9474)
