### ISSUE TITLE
UX-UI Page de résultat

### ISSUE THREAD

**Issue by martinregner** [datagir/nosgestesclimat-site#266]
Le "Passer à l'action" peut être coupé selon l'écran (ex. ci-dessous).
Un prospect m'a dit hier qu'il avait pas vu le bouton...

Possible de réduire un peu quelques espaces ? ou de **mettre le bouton dans la partie orange** ? C'est passer à l'action pour diminuer le résultat, en terme d'UX ça me parait se tenir.

![image](https://user-images.githubusercontent.com/46482115/120767463-802aa780-c51b-11eb-976f-b177a912bec6.png)

**Comment by laem** [comment]
Eh bien je trouve ça relativement élégant en déplaçant simplement le bandeau existant, qui a l'avantage de couper en deux et séparer l'introduction du graphique complémentaire. 

![Capture d’écran du 2021-06-08 18-47-42](https://user-images.githubusercontent.com/1177762/121225643-05022200-c88a-11eb-9afb-3bd701fb317c.png)


![Capture d’écran du 2021-06-08 18-46-20](https://user-images.githubusercontent.com/1177762/121225466-d5531a00-c889-11eb-9357-ad49e157f46f.png)
