### ISSUE TITLE
NGC conférence : Nom de salle par défaut

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/nosgestesclimat-site#273]
Aujourd'hui on propose automatiquement un nom de salle par défaut et c'est peut-être pas forcément très clair pour l'utilisateur
**Proposition :** 
- Laisser le champs libre pour saisir un nom de salle avec le typing qui clignote par ex 
- Et laisser le bouton "Générer un nom automatique (ou générer un autre nom de salle)

Qu'en pensez-vous ?

**Comment by laem** [comment]
> Laisser le champs libre pour saisir un nom de salle avec le typing qui clignote par ex

On en a discuté avec @florianpanchout, mettre le focus sur le champs de saisie fait ouvrir le clavier sur mobile notamment, ce qui est trop perturbant.

> Aujourd'hui on propose automatiquement un nom de salle par défaut et c'est peut-être pas forcément très clair pour l'utilisateur

Quel est le problème dans l'implémentation actuelle à ton avis ? Il y a quand même plusieurs indices qui montrent que le nom de salle peut être choisi : 
- "💡 Choisissez un nom de salle "
- le champs input qui est un standard Web
- la croix rouge qui permet d'effacer le nom et d'en taper un 

Les statistiques nous montrent aussi que beaucoup d'utilisateurs choisissent un nom de salle propre :+1:

**Comment by florianpanchout** [comment]
La croix rouge s'affiche comme ça chez moi : 

![Screenshot 2021-06-14 at 15 45 26](https://user-images.githubusercontent.com/8115933/121902422-990b3800-cd27-11eb-8428-0600924a512d.png)

Et sinon pour rendre l'édition du champ plus évident : 
- Mettre le contenu par défaut en placeholder. C'est un comportement assez standard maintenant sur le web.
- Afficher la croix rouge et le bouton générer inline

**Comment by laem** [comment]
> La croix rouge s'affiche comme ça chez moi 
Oui c'est noté par Martin sur https://github.com/datagir/nosgestesclimat-site/issues/272, en cours de résolution dans #278 

Je merge :+1
