### ISSUE TITLE
Mettre à jour les champs "Moyenne d'un français" sur le bilan

### ISSUE THREAD

**Issue by martinregner** [datagir/nosgestesclimat-site#282]
Retour reçu sur la boite contact.
La "moyenne" sur : 
- l'écran de fin
- l'écran conférence

est restée statique non ?

>Je vois que votre outil utilise l'empreinte carbone moyenne d'un français pour comparer les émissions du testeur à celle d'un français moyen. C'est donc une donnée importante puisque se comparer à son semblable est un puissant levier d'action. Quand on est au-dessus d'une moyenne, on a tendance à vouloir faire tout notre possible pour repasser dessous et faire mieux que la norme.

> L'empreinte carbone moyenne d'un français a été révisée par le Service de la donnée et des études statistiques (SDES) en 2020 [1]. Elle est estimée à 9,9 tCO2e / français en 2019 (vs. 11,2 tCO2e en 2018 dans la version SDES 2019 [2]). 

> Glossaire & sources :
SDES : service statistique ministères chargés de l’environnement, de l’énergie, de la construction, du logement et des transports

> [1] SDES 2020 : https://www.statistiques.developpement-durable.gouv.fr/estimation-de-lempreinte-carbone-de-1995-2019?rubrique=27&dossier=1286

> [2] SDES 2019 : https://www.statistiques.developpement-durable.gouv.fr/sites/default/files/2020-01/datalab-essentiel-204-l-empreinte-carbone-des-francais-reste-%20stable-janvier2020.pdf

**Comment by laem** [comment]
Bien vu ! ça faisait illusion auparavant. J'en ai fait une valeur calculée sur les valeurs par défaut, pour que tout soit cohérent avec notre modèle :)
