### ISSUE TITLE
La distinction "mode guidé" / "mode autonome" n'est pas comprise

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#292]
A confirmer avec d'autres tests utilisateur, mais ça semble être une complexité malvenue, surtout que les utilisateurs n'arrivent pas naturellement sur l'écran action...

Sentiment de passer d'une expérience facile (le test) à quelque chose de confus (les actions).

**Comment by Clemog** [comment]
Plus d'acte :)
