### ISSUE TITLE
Mode conférence/sondage pour un territoire

### ISSUE THREAD

**Issue by fjg** [datagir/nosgestesclimat-site#294]
Demande pour l'utiliser sur un territoire (15k citoyen·ne·s) :

- [x] Quelle est la charge maxi possible en 1 session, 100 personnes ? 

- [x] Est-ce possible d'exporter les résultats dans un Excel/CSV pour faire des stats et agréger le résultat de plusieurs sessions ?

- [x] possible que des personnes utilisent le lien de conférence/groupe en mode asynchrone et ajoute leur résultat perso ? (et donc l'orga pourrait... <suite au point ci-dessous>)

- [x] exporter les résultats agrégés de tests faits de manière async sur 10 jours par exemple) ou sinon est-ce que chaque individu qui ferait le test peut exporter son résultat ?

L'objectif est de pouvoir exporter les résultats de session __conférence__ et __sondage__ (asynchrone) pour avoir des stats sur un terrritoire.

**Comment by Clemog** [comment]
Tout est possible :)
