### ISSUE TITLE
Problème génération image de partage sur les réseaux

### ISSUE THREAD

**Issue by Benbb96** [datagir/nosgestesclimat-site#297]
J'ai fait un fork du repository : https://github.com/TimeForThePlanet/nosgestesclimat-site afin de personnaliser l'écran de fin du calculateur pour Time for the Planet et j'aimerai maintenant améliorer l'image de rendu lorsque l'on partage le lien sur les réseaux sociaux mais je rencontre des difficultés.

J'ai vu dans le code que vous utilisez un système de screenshot (hébergé sur Netlify) afin de créer l'image dans le meta tag : https://github.com/datagir/nosgestesclimat-site/blob/09aabb9be695ace3b66619716dac7ce7de12c6eb/source/sites/publicodes/Fin.js#L79

J'ai donc essayé d'utiliser ce système mais cela n'a pas l'air de fonctionner. Nous avons déployé le calculateur à cette adresse : http://ngc.time-planet.fr/
Et l'image qui devrait être affiché lors d'un partage devrait être celle-ci (sur une nouvelle page que j'ai créé) : http://ngc.time-planet.fr/shared-ending-screen?details=a1.69s1.11n0.56d0.11t0.10l0.09
Mais visiblement, l'outil sur Netlify ne la génère pas correctement : https://aejkrqosjq.cloudimg.io/v7/http://ngc.time-planet.fr/.netlify/functions/ending-screenshot?pageToScreenshot=http://ngc.time-planet.fr/shared-ending-screen?details=a1.69s1.11n0.56d0.11t0.10l0.09

Pourtant, j'ai regardé le code de la fonction Netlify (https://github.com/datagir/nosgestesclimat-site/blob/master/functions/ending-screenshot.js), j'ai donc bien gardé l'ID `shareImage` mais je ne vois pas d'où provient l'erreur..

**Comment by laem** [comment]
Dans #299, j'enlève la dépendance à cloudimg.io.

Cela dit, je suspecte que le problème vient d'ailleurs : est-ce que tu utilises netlify pour héberger le site ? Dans ce cas, as-tu activé les fonctions si nécessaire  ? 

Car quand on essaie cette URL, on n'obtient pas la fonction mais le site avec une 404. 

http://ngc.time-planet.fr/.netlify/functions/ending-screenshot?pageToScreenshot=http://ngc.time-planet.fr/shared-ending-screen?details=a1.69s1.11n0.56d0.11t0.10l0.09

**Comment by Benbb96** [comment]
Effectivement, on avait déployé le site via Google Cloud Platform.

Je me demande, en quoi est-ce nécessaire de passer par une fonction Netlify ? Peut-on arriver à faire un screenshot en passant par le routing de React et à servir l'image dans la meta tag ?

**Comment by laem** [comment]
Facebook & co ne supportent pas l'image binaire dans le meta tag. Il faut forcément référencer une URL https://xxxx.png. Sinon oui, générer l'image côté client était une bonne piste pour ne pas dépendre d'un serveur. 

L'avantage, c'est que les fonctions Netlify / AWS ne sont presque pas des serveurs, zéro maintenance.

**Comment by laem** [comment]
Tu as tous les détails de l'implé ici : https://github.com/datagir/nosgestesclimat-site/pull/208

**Comment by Benbb96** [comment]
@laem,

Nous avons redéployé notre site via Netlify et la fonction pour générer l'image de partage est maintenant fonctionnelle : https://ngc.time-planet.com/.netlify/functions/ending-screenshot?pageToScreenshot=https://ngc.time-planet.com/shared-ending-screen?details=s1.11l1.08a1.07n0.28d0.16t0.15 👍 

Cependant, lorsque l'on partage l'url de l'écran de fin (par exemple : https://ngc.time-planet.com/fin?details=s1.11l1.08a1.07n0.28d0.16t0.15), cela prend toujours l'image par défaut (https://nosgestesclimat.fr/dessin-nosgestesclimat.png).

Est-ce qu'il faut que nous mettions en place cloudimg.io de notre côté également ? Quel est sont utilité ?

**Comment by Clem-mrtn** [comment]
Les points d'optimisation : 
- Rajouter peut-être le logo TFTP à côté de NGC plutôt qu'en page de fin
- "Passer à l'action" : au lieu de le mettre sous forme de CTA avec un bouton, le mettre en plus petit en mode "phrase cliquable" "Vous souhaitez aller plus loin : passez à l'action"

**Comment by florianpanchout** [comment]
Hello,

J'ai fait quelques modifications sur la page de fin, qui ressemblerait maintenant à ça :

![Screenshot 2021-07-20 at 11 23 32](https://user-images.githubusercontent.com/8115933/126297203-28cae9bf-2ca9-46ec-a962-0dfcacde268c.png)

Est ce que vous pourriez m'autoriser sur votre repo pour que je puisse push la branche que j'ai créé ?

**Comment by Benbb96** [comment]
Super, merci beaucoup pour ton aide ! Je viens de te donner les droits d'écriture sur le fork 😉

**Comment by florianpanchout** [comment]
Merci ! La branche est ici : https://github.com/TimeForThePlanet/nosgestesclimat-site/tree/endpage 

Je vous laisse checker et merger si ça vous convient :)

**Comment by Clem-mrtn** [comment]
@Benbb96 si c'est OK pour Arthur et toi, je vous laisse mettre en prod pour qu'on test la mise en ligne :)

**Comment by Benbb96** [comment]
@florianpanchout, @Clem-mrtn
Je viens de faire le merge sur notre fork. Encore merci pour l'aide apporté !
Il ne restera plus que le problème de la génération de l'image de partage à régler (il s'agit probablement d'un temps trop long pour charger l'image dynamique).

@ALSAREM est-ce que tu pourras redéployer la nouvelle version s'il te plaît (à moins que cela ne se fasse tout seul ?)

**Comment by Clem-mrtn** [comment]
@Benbb96 je sais pas si tu as vu avec Arthur mais il me semble qu'il voulait juste changer le wording de "Découvrir Time for the Planet" pour "Agir avec Time for the planet" ?

**Comment by Benbb96** [comment]
@Clem-mrtn Non je n'ai pas encore rediscuté du projet avec Arthur depuis quelques jours déjà.
Mais je vais faire cette petite modif', ça me semble mieux en effet !

**Comment by Clemog** [comment]
Je ferme cette issue, n'hésitez pas à la réouvrir si besoin !
