### ISSUE TITLE
Fonction export des résultats

### ISSUE THREAD

**Issue by martinregner** [datagir/nosgestesclimat-site#301]

**Comment by laem** [comment]
Encore une fois sur cette fonctionnalité, il va falloir se poser la question de la RGPD. 
Sans export, les données restent sur nosgestesclimat.fr, sauf à les capturer en photo / si quelqu'un les "scrape". 

Avec export, elles peuvent être facilement utilisées pour autre chose.

**Comment by laem** [comment]
Fixed by #444 au moins pour le mode sondage. Je pense qu'il faut éviter cette fonctionnalité pour le mode conférence, plus respectueux de la vie privée.
