### ISSUE TITLE
NGC conférence : lien invalide lorsque l'on se connecte sur une salle depuis les réseaux sociaux 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/nosgestesclimat-site#324]
Lors de me tests utilisateurs sur NGC conférence j'ai remarqué que lorsque l'on partage le lien d'une salle sur les RS, et qu'on ouvre cette salle depuis l'application du RS en question on tombe sur une page erreur.
J'explique mon parcours : 
- Je créé une salle et je partage le lien sur Messenger 
- Je tente d'ouvrir le lien de la salle depuis l'application Messenger 
- Je tombe sur une page erreur 
- Je dois cliquer sur "ouvrir dans safari" pour avoir accès au lien

![Capture d’écran   2021-08-26 à 17 19 54](https://user-images.githubusercontent.com/76995768/130990408-951baca8-f9ed-449f-b04e-eddd09c03196.png)

=> J'ai l'impression que l'application bloque l'ouverture du lien ? Pas top top pour la fonction de partage

**Comment by Clemog** [comment]
Est ce qu'on peut tester à nouveau ? 
Je me demande si ce n'est pas un problème d'accent .. Je crois qu'on a eu un problème similaire au ground control avec un lecteur de QR code qui ne retranscrivait pas correctement l'url

**Comment by Clem-mrtn** [comment]
Aujourd'hui quand je reproduis le test tout fonctionne, que ce soit : 
- sur les RS sur ordinateur
- Depuis les apps de mon smartphone 
- Avec ou sans accent dans le nom de la salle 

![300337835_469142721487374_1934184535276184278_n](https://user-images.githubusercontent.com/76995768/185927567-73a3d265-d7d5-43e9-aa54-c8f0460c33e6.jpg)
![300855993_829994364825847_5365223997772272424_n](https://user-images.githubusercontent.com/76995768/185927568-2f992ff5-0ed4-4802-b8f7-bfe78d671f16.jpg)
