### ISSUE TITLE
Pas possible de revenir sur sa simulation après écran de fin

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#325]
Vient probablement de la PR de réintégration du bouton retour. Assez simple à régler.

**Comment by Clem-mrtn** [comment]
![Uploading image.png…]()
Je confirme que j'ai toujours le même problème ... je ne peux plus refaire la simulation sauf en navigation privé .....

**Comment by laem** [comment]
Je suspecte que c'est du à une MAJ des règles de calcul, mais je n'ai toujours pas réussi à reproduire :/ 
En attendant, tu peux supprimer les données du site à la main dans les options du navigateur.
Normalement, ce sera résolu dans la nouvelle version. Je crois que ça ne touche pas grand monde, à en juger par le peu de retour dans ce sens.
