### ISSUE TITLE
Traitement des réutilisateurs du code

### ISSUE THREAD

**Issue by martinregner** [datagir/nosgestesclimat-site#330]
_NGC Campus, version entreprise, version sport_ ... propositions pour positionner ces "enfants" externes de NGC.

Communication pour eux du lien entre les outils : mettre un bandeau texte sur la page d'accueil
> **Cette déclinaison s'appuie librement sur la version officielle de [Nos Gestes Climat](https://nosgestesclimat.fr/) développé par l'[ABC](https://www.associationbilancarbone.fr/) et [Datagir (ADEME)](https://datagir.ademe.fr/)**.

**Sauf accord explicite, les logos ABC et ADEME ne sont pas affichés sur ces outils.**

To do : 
- [x] Documentation avec guidelines spécifiques notamment sur les modalités de réutilisation (avec éléments de langage ci-dessus) + rappel de la [licence](https://github.com/datagir/nosgestesclimat/blob/master/LICENSE)
- [x] Section spécifique (sur NGC ? sur datagir.ademe.fr ?)
- [ ] dans le code : intégrer les logos seulement si une variable d'environnement est intégrée

**Comment by laem** [comment]
Je fais une nouvelle issue pour le 3ème point, plus compliqué.
