### ISSUE TITLE
Mauvaises propositions d'actions en fin de simulation

### ISSUE THREAD

**Issue by avenirclimatique** [datagir/nosgestesclimat-site#340]
Bonjour,

Retour d'utilisation de la partie "Plan d'action" par une utilisatrice.
L'utilisatrice indique ne pas voyager en avion. L'utilisatrice dispose d'une voiture et a effectué 16 000 km en 2019. L'utilisatrice n'utilise pas la voiture pour aller au travail, car elle est en télé-travail tous les jours (salariée de l'APCC). Pour les grands trajets, elle propose un covoiturage sur Blablacar, sauf lorsqu'elle emmène son chien et sa famille dans le véhicule.
Le module plan d'action lui propose :
- De ne pas voyager en avion (avec 0% de réduction, car 0 km en avion)
- De remplacer les voyages en avion par voyage en train (avec 4% de réduction... ???)
- D'aller au travail en covoiturage,
- D'aller au travail en transport en commun,
- De faire du télé-travail (c'est déjà le cas, 5j par semaine)

Idem pour moi, qui vait au travail en vélo. Je crois qu'il y a un peu plus de contexte à demander dans le formulaire pour un besoin de cohérence avec le plan d'action.

**Comment by Clemog** [comment]
J'ai l'impression que la possibilité d'écarter les actions et les questions posées avant de permettre la sélections résout une partie du problème :)
