### ISSUE TITLE
Ajout vidéo tutoriel page accueil mode Conférence

### ISSUE THREAD

**Issue by Benjamin-Boisserie-ABC** [datagir/nosgestesclimat-site#343]
La vidéo tutorielle du mode Conférence serait plus pertinente si elle était intégrée dans la page d'accueil du mode Conférence

On pourrait avoir un message en haut ou bas de page "découvrez très rapidement avec cette vidéo comment utiliser le mode conférence"

@laem @martinregner qu'en pensez-vous ?

**Comment by Clemog** [comment]
La vidéo est dans la doc Datagir :)
