### ISSUE TITLE
Accessibilité

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#350]
Le site n'est actuellement [décembre 2021] pas accessible : voici un premier audit relevant de nombreux problèmes (mais aussi quelques bonnes choses) 

:arrow_right: :bookmark_tabs:  https://hellobokeh.notion.site/Nos-Gestes-Climats-4e4694c14e5345f5a465e95db8b04697

**Comment by laem** [comment]
Voir #419

**Comment by laem** [comment]
Nous sommes actuellement en période d'audit.

**Comment by Clemog** [comment]
L'audit est terminé, des améliorations sont toujours à prévoir :) #572 #575
