### ISSUE TITLE
Pouvoir faire varier le seuil d'exclusion dans les conférences

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#353]
On doit le faire pour tout le monde, pour que tout le monde voit la même chose. 
À cacher en bas pour que l'admin s'en saisisse.
@Benjamin-Boisserie-ABC

**Comment by Benjamin-Boisserie-ABC** [comment]
Oui je pense que c'est une bonne idée que cela soit cachée et que seul l'admin puisse s'en saisir.

**Comment by laem** [comment]
Fixed by #444, PR du mode sondage. 

Par défaut je l'ai mis à 100, et chaque utilisateur peut le régler. Il est assez discret. On refera une issue si problème avec l'implé.

**Comment by Benjamin-Boisserie-ABC** [comment]
Quelques petits retours suite à l'évolution du mode conférence @laem 
1. Pourrait-on sélectionner (afficher en jaune) une empreinte aussi en cliquant sur l'empreinte d'un poste et pas seulement en cliquant sur l’empreinte globale
2. Dès qu'un participant quitte le mode conférence (en fermant sa page NGC) puis y revient cela compte un participant supplémentaire (ce qui fausse le nombre réel de participants). Est-ce que c'est possible de palier à cela ou non ?
3. Il y a un petit bug d'affichage 
![image](https://user-images.githubusercontent.com/66410914/159232947-693925b5-6d07-4b89-af82-4cb285a15eb3.png)

**Comment by laem** [comment]
J'en fait une nouvelle issue
