### ISSUE TITLE
Valoriser davantage la barre d'avancement des questions

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/nosgestesclimat-site#357]
Aujourd'hui la barre d'avancement n'est pas bien vue, ni distinguée :  ce qui peut être perçu comme frustrant pour l'usager, qui ne sait pas où il en est sur son test. 

Idées : 

- Bien dissocier la barre déjà existante du bandeau 
- Ecrire X questions / X 
- Autres

**Comment by Clemog** [comment]
Avancement désormais dans le menu à gauche :)

**Comment by Clem-mrtn** [comment]
C'est pas mal du tout ! 👍 
Peut-être un peu petit, risque peut-être de ne pas être bien vu par l'utilisateur mais ça se teste dans l'usage !
