### ISSUE TITLE
Repositionner la question "Zéro déchet" 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/nosgestesclimat-site#358]
Aujourd'hui la question zéro déchet est la première question liée à l'alimentation : peut-être un peu difficile de prime abord.
La repositionner en 3ème ou 4ème position (après la question sur l'eau en bouteille?)

**Comment by Clemog** [comment]
Aujourd'hui l'ordre est généré par un algorithme selon le score de chaque règle (calculé notamment en fonction du nombre de variable dont dépend une question par exemple). La PR #568  a intégré la possibilité d'afficher des questions en prioritaire. Ce n'est pas forcément une bonne chose car il est nécessaire de "faire attention" à cette liste en cas de changement de règles..
