### ISSUE TITLE
Questionnaire-Rubrique Numérique : Décocher les réponses aux Q.

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/nosgestesclimat-site#372]
Dans le questionnaire, partie numérique, les réponses aux questions sont pré-cochées.
Malheureusement cela est contre intuitif pour l'utilisateur suite aux nombreux retours (cf. #337 par exemple)

**=> Il faudrait revenir à un système plus classique et plus simple où l'utilisateur a juste à cocher lui même les cases des produits numériques qu'il possède**

**Comment by laem** [comment]
Avant 

![coche-avant](https://user-images.githubusercontent.com/1177762/140096543-0c51e401-20f2-4b94-8d9f-fd756445faee.gif)

Après

![coche-après](https://user-images.githubusercontent.com/1177762/140096534-e5f44949-080d-4f39-a29f-a2fcbc617fc5.gif)
