### ISSUE TITLE
Petit bug saisie NumberedMosaic

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#380]
Suite à #378

> - De mon côté, j'ai un bug quand je rentre une valeur à la main que je souhaite finalement modifier : lorsque j'efface j'ai 0 qui s'affiche et il reste au début du nombre que je rentre dans un deuxième temps. Je sais pas trop comment on peut résoudre le problème, j'ai l'impression que c'est la valeur de la variable donc forcément affichée

> - Ah oui, en effet étrange. Surtout pour un input type number. On dirait qu'il agit comme un string. J'en fais une issue.

**Comment by Clemog** [comment]
Sera résolu dans #601 :)
