### ISSUE TITLE
Bug iframeResize

### ISSUE THREAD

**Issue by Benbb96** [datagir/nosgestesclimat-site#414]
Je viens de créer un nouveau repo pour intégrer l'iframe paramétrable (en lien avec Time for the Planet) et j'ai pu la déployer via Github Page. Mais je rencontre une drôle d'erreur lorsque je réponds aux questions du tutoriel : la page s'agrandit toute seule.
Je suppose donc qu'il y a un soucis avec la fonction `iframeResize` car le problème n'existe pas sur le site officiel de NGC.

Pour tester directement sur la page : https://timefortheplanet.github.io/nosgestesclimat-iframe/

**Comment by laem** [comment]
Ah oui, en effet, je confirme !

**Comment by laem** [comment]
Le problème n'apparait pas cependant sur une intégration comme https://datagir.ademe.fr/apps/nos-gestes-climat/

Je vais investiguer

**Comment by laem** [comment]
Salut @Benbb96, j'ai mis en ligne une correction, dis-moi si ça le fait :)

**Comment by Benbb96** [comment]
Hello @laem oui c'est parfait, je n'ai plus le soucis après avoir vidé le cache !

Notre site avec l'iframe est désormais fonctionnel ici : https://ngc.time-planet.com/ 😃
