### ISSUE TITLE
gaz/électricité verte

### ISSUE THREAD

**Issue by jacosalzero** [datagir/nosgestesclimat-site#416]
bonjour

pourquoi n'y a -t-il pas de disctinction selon son offre d'électricité, avec des opérateurs reconnus comme Enercoop. Dans le Mic Mac on avait cette distinction.

Merci!

**Comment by laem** [comment]
Bonjour, je vous laisse consulter la FAQ, la réponse y est : https://nosgestesclimat.fr/contribuer
