### ISSUE TITLE
Bug retour arrière mosaïque

### ISSUE THREAD

**Issue by Clemog** [datagir/nosgestesclimat-site#426]
Un bug remonté à plusieurs reprise par les utilisateurs : les mosaïques regroupant plusieurs questions, le bouton précédent doit être cliqué plusieurs fois avant que le retour soit effectif.

https://user-images.githubusercontent.com/55186402/147109058-edbcde6f-e0e4-4324-8970-880191a3db51.mov

**Comment by laem** [comment]
Oui il faut cliquer autant de fois que de questions gérées par la mosaïque en question, c'est quelque chose qu'on aurait du régler dès le début de l'implé de la conférence, bien vu !

**Comment by laem** [comment]
@Clemog normalement résolu ici : 
https://github.com/datagir/nosgestesclimat-site/blob/1080c239a581cff5022d9d6328876fb15da55bc7/source/components/conversation/Conversation.tsx#L119-L124

dans la PR #428 où je corrige les derniers bugs. 

Je te laisse tester que ça résoud le problème sans en introduire un nouveau avant de fermer cette issue.

**Comment by Clemog** [comment]
Top, c'est bon pour moi :)
