### ISSUE TITLE
bien conçu mais manque de transparence sur les calculs 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat-site#431]
Bonjour, on reconnaît derrière ce calculateur le "Micmac". Je trouve l'interface très bien conçue, avec des améliorations de présentation vs le Mic MAc, mais ça manque de transparence sur les calculset hypothèses (donc 1/difficile de voir d'éventuelles "corrections" 2/ ne permet pas de simuler un changement de comportement). Par ailleurs une question de fond sur les actifs financiers : leur impact n'est il pas déjà compté dans la consommation des produits/de l'énergie issus des entreprises financées ? Merci. Jacques Salzer

**Comment by Clemog** [comment]
Cf #346
