### ISSUE TITLE
Proposer plusieurs durée de sondages

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#457]
1 jour / 1 semaine / 2 semaines par exemple. 

On fixe le temps pour deux raisons : 
- ne pas accumuler d'historique trop long chez nous
- ne pas cumuler des résultats de tests avec des algos trop hétérogènes suite à changements de modèle

**Comment by lbranaa** [comment]
On ferme car on a finalement décidé de proposer uniquement une durée de sondage de 2 mois pour ne pas complexifier.
