### ISSUE TITLE
Ascenseur inutile sur cartes persona

### ISSUE THREAD

**Issue by martinregner** [datagir/nosgestesclimat-site#458]
![image](https://user-images.githubusercontent.com/46482115/155143362-cc5d9700-c64f-4397-a4ca-ecaf55cbc8ff.png)

**Comment by laem** [comment]
@martinregner c'est sur quel navigateur / résolution ?

**Comment by martinregner** [comment]
Sorry.
Chrome PC v99

**Comment by Clemog** [comment]
C'est toujours le cas ?

**Comment by martinregner** [comment]
Oui toujours pour moi (chrome v104)

**Comment by Clemog** [comment]
C'est bon normalement :)
