### ISSUE TITLE
Clic sur les cartes avec case à cocher

### ISSUE THREAD

**Issue by mquandalle** [datagir/nosgestesclimat-site#462]
On s'attend à pouvoir cliquer sur l'ensemble de la carte pour cocher la case à l'intérieur

![bug ngc](https://user-images.githubusercontent.com/1730702/155848202-af4367f1-0d05-4981-95ac-76631d3805ea.gif)

**Comment by Clemog** [comment]
Résolu dans #568 normalement :)
