### ISSUE TITLE
Traduction Anglaise 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/nosgestesclimat-site#470]
- Passer par une API type Deeple ?
- Passer par le marché de traduction de l'ADEME ?

/!\ Eviter les word, passez directement par du markdown pour éviter le double travail. 
Est-ce que l'ADEME sait faire ?

**Comment by laem** [comment]
Je pense qu'on a tout intérêt à privilégier l'option API d'abord. Ne serait-ce que parce que faire appel à des traducteurs via un marché, c'est nous imposer un délai de plusieurs semaines à chaque publication de nouvelle PR contenant du texte (donc presque toutes). 
Ce qui n'empêche pas de faire des relectures d'amélioration avec des traducteurs pro :)

**Comment by martinregner** [comment]
> Est-ce que l'ADEME sait faire ?

Est-ce que les prestataires savent faire ? Sans doute pas... sauf à prendre un.e dev ;)

> nous imposer un délai de plusieurs semaines à chaque publication de nouvelle PR contenant du texte

En effet, ce n'est pas du tout l'objectif.
Une relecture épisodique de la traduction automatique est bien plus pérenne et efficace 👍

**Comment by laem** [comment]
Cas d'usage qu'on nous a communiqué : 

> Principalement pour mes collègues anglophones en Suisse. 
> Évidemment une adaptation au marché suisse serait idéale

**Comment by laem** [comment]
Lié à #549

**Comment by Clem-mrtn** [comment]
- [ ] Commencer à réfléchir aux différentes solutions à implémenter 
- [ ] Se faire un point cette semaine pour en discuter

**Comment by EmileRolley** [comment]
Closed by https://github.com/datagir/nosgestesclimat-site/pull/641 and https://github.com/datagir/nosgestesclimat/pull/1522
