### ISSUE TITLE
Quelques améliorations du mode groupe

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#495]
Quelques petits retours suite à l'évolution du mode conférence @laem 
1. Pourrait-on sélectionner (afficher en jaune) une empreinte aussi en cliquant sur l'empreinte d'un poste et pas seulement en cliquant sur l’empreinte globale
2. Dès qu'un participant quitte le mode conférence (en fermant sa page NGC) puis y revient cela compte un participant supplémentaire (ce qui fausse le nombre réel de participants). Est-ce que c'est possible de palier à cela ou non ?
3. Il y a un petit bug d'affichage 
![image](https://user-images.githubusercontent.com/66410914/159232947-693925b5-6d07-4b89-af82-4cb285a15eb3.png)

**Comment by Clemog** [comment]
J'ai corrigé les points 1 et 3 dans la PR #512, j'ai du mal à comprendre le point 2 ?

**Comment by Clemog** [comment]
Corrigé dans #512, je te laisse vérifié @laem :)
