### ISSUE TITLE
La popup de partage mal placé

### ISSUE THREAD

**Issue by Sacramentix** [datagir/nosgestesclimat-site#508]
La pop qui apparait pour permettre de partager les résultats à un tier via une iframe ne s'affiche pas en de manière absolue comme avant.

Maintenant : 
![image](https://user-images.githubusercontent.com/35272156/163040336-cc1bb895-1144-4e9a-a636-b8cc2d7b1f64.png)

Avant: 
![image](https://user-images.githubusercontent.com/35272156/163040739-6f4f6a8a-ecde-467d-9a91-74f87f55a692.png)

**Comment by Clemog** [comment]
Résolu dans #515, je ferme :)
