### ISSUE TITLE
Comportement précédent

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#510]
Quand on revient de la question C à la B, qu'on change B, puis qu'on clique précédent pour aller à A, B n'est pas revalidée avec la nouvelle valeur. 

À étudier, pas trivial.

**Comment by Clemog** [comment]
Je viens de tester, il me sembler que c'est résolu !

**Comment by laem** [comment]
OK, je ferme jusqu'à nouvel ordre.
