### ISSUE TITLE
BUG Iframe site Agir

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/nosgestesclimat-site#513]
Suite au retour d'un utilisateur, il y a en effet un bug dans l'affichage de _l'iframe_  sur le site Agir : 
> il y a un problème technique sur votre site internet.
https://agirpourlatransition.ademe.fr/particuliers/testez-vos-connaissances/connaissez-empreinte-climat
Lorsque vous cliquez sur "Faire un test à plusieurs", l'intégration ne fonctionne pas. Nous ne pouvons pas scroller.
C'est la même chose pour d'autres parties de l'intégration.

Cf capture : 
![image](https://user-images.githubusercontent.com/76995768/164041806-82806038-f34f-4462-aad4-d85f336e7414.png)

=> @Clemog @laem pouvez-vous regarder ce qu'il en est ? Merci 🙏

**Comment by laem** [comment]
Ah merci !!! C'est la solution au nombreuses issues récentes. 

Celles sur l'électroménager. 

![image](https://user-images.githubusercontent.com/1177762/164043561-89a32d71-b0b7-4828-b0e5-c59fac44ff7d.png)

Ce qu'il se passe, je crois, c'est que l'ADEME n'a pas utilisé notre script d'intégration d'iframe, mais leur iframe à eux, qui est bloqué en hauteur. Du coup ça casse toute l'expérience du site.

**Comment by Clem-mrtn** [comment]
Ah zut ! Qui on peut contacter côté site Agir @martinregner pour leur demander de remplacer le script d'intégration pour éviter le problème ?

**Comment by martinregner** [comment]
Oui. Le mieux pour les pages grand public est de passer par Florence.
Je peux te laisser lui écrire @Clem-mrtn ?

**Comment by Clemog** [comment]
J'ai l'impression que l'iframe n'est plus sur le site ? 
https://agirpourlatransition.ademe.fr/particuliers/actualites/mesurez-empreinte-carbone-gestes-climat-site-datagir

**Comment by Clem-mrtn** [comment]
C'est parce qu'il a été intégré sur cette page là : https://agirpourlatransition.ademe.fr/particuliers/testez-vos-connaissances/connaissez-empreinte-climat

**Comment by Clemog** [comment]
Est-ce qu'on relance pour qu'ils modifient leur intégration ?

**Comment by martinregner** [comment]
Modifier car l'iframe est mal paramétré ? (ne s'affiche pas en version "mobile" mais "bureau" pour moi par ex. c'est moins facile à remplir)
Tu peux demander le contact technique à Florence et Marilyne sur le teams oui 👍

**Comment by laem** [comment]
Je ferme, n'hésitez pas à rouvrir si toujours pertinent.
