### ISSUE TITLE
Retour en arrière non fonctionnel

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat-site#516]
Je n'arrive pas à revenir en arrière pour modifier la consommation électrique de mon foyer

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Résolu par #478 normalement ?

**Comment by laem** [comment]
Mmmh, tu penses ?

**Comment by martinregner** [comment]
On m'a encore remonté encore quelques bugs sur le "précédent" (lors d'un sondage)

**Comment by Clemog** [comment]
Je ferme au profit de #642
