### ISSUE TITLE
Enquête utilisateurs

### ISSUE THREAD

**Issue by florianpanchout** [datagir/nosgestesclimat-site#517]
Ce serait intéressant, vu le volume de visites, de poser des questions ("Comment avez vous connu NGC", "Notez votre connaissance des enjeux climatiques", etc.) directement à nos utilisateurs pour élaborer des personas.

Qu'est ce que vous pensez d'afficher une modal sur la home afin d'inviter les visiteurs à répondre à une enquête ?

**Comment by laem** [comment]
👍 et peut-être qu'on pourra utiliser le travail fait sur #512

**Comment by Clemog** [comment]
Super idée ! 
Ça rejoint un peu une réflexion qu'on a eu sur l'introduction d'une question au milieu ou à la fin du test pour avoir une idée de la "réception" du simulateur :)
https://github.com/datagir/nosgestesclimat-site/issues/465

**Comment by Clem-mrtn** [comment]
Les résultats de l'étude permettront d'attaquer les chantiers #355 #511

**Comment by Clemog** [comment]
Pour le moment, on ne mènera pas d'enquête spécifique utilisateurs NGC, on peut dans un premier tracker mieux pour cartographier les comportements des utilisateurs (lié à #443)

**Comment by Clemog** [comment]
Issue réouverte ! On pourrait intégrer un formulaire à l'image de celui sur MCCO2 (https://github.com/datagir/monconvertisseurco2/issues/102)

**Comment by Clem-mrtn** [comment]
J'ai dupliqué le form, vous pouvez le modifier [ici  ](https://airtable.com/appdsewDZTOchqILN/tblmBi2IjnItwziQG/viwwrtNRo5HVby1B2?blocks=hide)

J'ai adapté le questionnaire à NGC : https://airtable.com/shrViXiiUo6Z1PvR7

=>On pourrait tester de le positionner en Home ?

**Comment by Clem-mrtn** [comment]
- [ ] Mise en ligne cette semaine en même temps que MCCO2

**Comment by laem** [comment]
L'enquête a été faite.
