### ISSUE TITLE
Récupérer les données de simulation

### ISSUE THREAD

**Issue by ysaintlary** [datagir/nosgestesclimat-site#525]
Bonjour,

J'ai suivi vos indications sur cette page : https://github.com/datagir/nosgestesclimat-site/blob/master/PERSONNALISATION.md#r%C3%A9cup%C3%A9rer-les-donn%C3%A9es-de-simulation. Et utilisé le code proposé sur codesandbox.io. Je vois bien les résultats remonter dans la console, merci !
Pouvez-vous donner des pistes de méthode pour agréger ces données en jquery vers csv par exemple ? Ou autre possibilité plus recommandée ?

Merci
Yves

**Comment by ysaintlary** [comment]
Voici la page où nous avons intégré le simulateur : https://weactforgood.com/nos-gestes-climat-calcul-impact-planete/
C'est un site Wordpress. 
Merci !

**Comment by ysaintlary** [comment]
Bonjour,
Est-ce qu'une solution d'enregistrement des résultats du simulateur est envisageable dans le cas que je vous présente ici ?
Comme précédemment, je pensais à une solution jquery + csv, mais peut-être que vous avez déjà expérimenté une solution de votre côté ?
Merci

**Comment by laem** [comment]
Nous n'avons pas la possibilité de vous aider à coder votre propre implémentation pour récupérer les données et en faire quelque chose. Nous vous permettons d'y accéder, mais nous ne pouvons pas aller plus loin. Vu qu'il s'agit de données utilisateur, mieux vaut y passer un minimum de temps. 

Mais quel est votre usage ? Quel est le service que vous voulez apporter à vos utilisateurs ?

**Comment by ysaintlary** [comment]
Bonjour Mael,
Merci pour votre réponse. L'usage serait simplement d'avoir des stats de réponse sur les utilisateurs du projet et éventuellement les présenter sur la page du calculateur.

**Comment by laem** [comment]
Je me permets de fermer vu la date. N'hésitez pas à rouvrir si besoin.
