### ISSUE TITLE
Fin de l'iframe personnalisé ? 

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#545]
Je vous propose de mettre fin à la possibilité d'intégrer l'iframe personnalisé. Je parle de la personnalisation de contenu et visuelle, mais pas du partage de données qui lui a carrément été développé par d'autres gens :) 

Pourquoi ? Ça nous prend du temps de maintenir cette fonctionnalité.
Elle est cassée depuis des mois (logo, vidéo youtube en fin de simu), et personne ne semble s'en être plaint. Nous n'avons pas non plus remarqué de grosse intégration utilisant cette possibilité. L'intégrer sur le nouvel écran de fin v3 prendrait encore du temps. 

Je crois que ça suit la tragédie des personnalisations : les gens ne les utilisent pas, sauf exception. Ils vont au plus simple. 

@Clemog @martinregner @Clem-mrtn

**Comment by Clemog** [comment]
On en a discuté je suis en phase !

**Comment by laem** [comment]
C'est acté
