### ISSUE TITLE
Ajouter le fil d'ariane pour la doc

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#561]
C'est à faire dans publicodes-react je crois. 

https://developers.google.com/search/docs/advanced/structured-data/breadcrumb#structured-data-type-definitions

**Comment by laem** [comment]
C'est géré par la nouvelle version de publicodes, sous la forme d'un menu. 
CF #653

**Comment by lbranaa** [comment]
@laem on peut donc fermer ?
