### ISSUE TITLE
Retourner à une question de la catégorie précédente depuis "Mon Profil"

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/nosgestesclimat-site#571]
Il y a un bug dans le parcours utilisateur pour revenir sur une question de la catégorie précédente

_Ex :_ une fois que j'ai répondu **aux questions alimentation**, et que je suis passée **à la catégorie Transport**, quand je vais sur Mon Profil et que je clique sur une question Alimentation, je suis **renvoyée automatiquement sur la catégorie en cours soit transport** et non la question sélectionnée => je ne peux pas modifier mes réponses.

Idem quand je clique sur Précédent, une fois le changement de catégorie, je ne peux revenir sur une question de la catégorie précédente.

**Comment by Clemog** [comment]
J'ai l'impression que c'est bon !

**Comment by Clem-mrtn** [comment]
Je confirme que les bugs ont été corrigés, je peux : 
- Revenir sur une question et modifier ma réponse depuis "Mon Profil" 
- Utiliser le Ctrl K pour rechercher une question 

Je ferme cette issue donc 👍
