### ISSUE TITLE
Certificat d'accessibilité 🎉 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/nosgestesclimat-site#572]
Nous sommes "officiellement" à 50% et sommes donc **Partiellement Accessible** ! 
- Afficher le certificat d'accessibilité sur le site Nos Gestes Climat
[instructions-publication-declaration-mention (1).pdf](https://github.com/datagir/nosgestesclimat-site/files/9008590/instructions-publication-declaration-mention.1.pdf)
[2022-06-15_nos-gestes-climat_declaration-accessibilite-RGAA4-1.docx](https://github.com/datagir/nosgestesclimat-site/files/9008591/2022-06-15_nos-gestes-climat_declaration-accessibilite-RGAA4-1.docx)
[20220629-2022-06-29_Grille-Recette_Nosgestesclimat_RGAA4.1.xlsx](https://github.com/datagir/nosgestesclimat-site/files/9008592/20220629-2022-06-29_Grille-Recette_Nosgestesclimat_RGAA4.1.xlsx)

**Comment by Clemog** [comment]
C'est assez frustrant, certaines remarques sont complètement à l'appréciation de chacun
<img width="889" alt="image" src="https://user-images.githubusercontent.com/55186402/176390702-bfb10192-536b-4bb7-975b-9ced3920a6c9.png">

**Comment by Clem-mrtn** [comment]
C'est une déclaration et non une certification, donc effectivement il y a des points qui sont p-t un peu subjectifs et laisser à l'interprétation mais c'est pas très grave pour le coup 
L'important c'était d'être "officiellement" à 50% et conserver les bonnes pratiques :)

**Comment by Clemog** [comment]
Je peux prendre une demi journée pour reprendre les points de détails qui sont mentionnés et peuvent être corrigés rapidement ?

**Comment by Clem-mrtn** [comment]
Up @Clemog
