### ISSUE TITLE
Hover sur la partie non cliquable des mosaïques 

### ISSUE THREAD

**Issue by florianpanchout** [datagir/nosgestesclimat-site#576]
Il y a un effet de hover sur les cadres des mosaïques, alors qu'elles ne sont pas cliquables (seul un élément à l'intérieur l'est). 

Ça ne m'a pas posé de problème (je ne l'ai même pas vu) pendant la simulation ([exemple](https://nosgestesclimat.fr/simulateur/bilan?cat%C3%A9gorie=logement,)), parce que la checkbox attire la souris.

Mais sur la [page personas](https://nosgestesclimat.fr/personas) je suis resté bloqué les premières fois, pensant à un bug.

Ma suggestion serait de réserver les effets au hover aux éléments interactifs. Ici cela passerait soit par rendre l'ensemble du cadre cliquable, soit par enlever l'effet au hover sur le cadre.

**Comment by Clemog** [comment]
Merci ! Sera corrigé ici : #568
