### ISSUE TITLE
Bug sur clic de "Choix de profil type"

### ISSUE THREAD

**Issue by Nab-88** [datagir/nosgestesclimat-site#577]
Bonjour,

J'ai remarqué un bug sur l'écran de choix d'un profil type dans l'onglet "Agir" (bug présent sur desktop et mobile).

Pour que la sélection du profil fonctionne il faut absolument cliquer sur "le nom du profil" (ou sur la zone autour), le clic sur l'ensemble de la tuile ne fonctionne pas alors que lorsqu'on est en hover dessus, la border devient violette.

Le bug est un peu plus problématique sur mobile car il n'y a pas de hover ni le pointeur de la souris, donc aucun moyen de se rendre que notre clic n'est pas pris en compte.

Voici un screen recording qui montre le pointeur de la souris en mode clic ou en mode edit.

https://user-images.githubusercontent.com/23705512/176688865-8046a2cf-8138-4633-a4dd-b8654e3632a3.mov

**Comment by Clemog** [comment]
Merci ! Sera corrigé ici : #568
