### ISSUE TITLE
Probleme de taille de la limite climat sur l'écran 2 de fin

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#581]
Pour >> 10 tonnes la barre verte ne réduit pas en taille, on a un souci.

**Comment by EmileRolley** [comment]
Il ne me semble pas avoir ce problème chez moi.. Le bug a-t-il été corrigé entre temps ?

**Comment by laem** [comment]
Tu es sûr ? Il s'agit de l'écran 2, le 1 est bon :) 

![image](https://user-images.githubusercontent.com/1177762/187475979-1e38fb98-8b57-42b0-8900-e7e199972e07.png)

**Comment by EmileRolley** [comment]
A oui tu as raison, mb...
