### ISSUE TITLE
Stats > Sélecteurs nombres et périodes blanc

### ISSUE THREAD

**Issue by martinregner** [datagir/nosgestesclimat-site#594]
Sur Chrome 103 PC :
![image](https://user-images.githubusercontent.com/46482115/180251806-f8ff978c-00c4-4612-9264-1e4c3b3c23c1.png)
![image](https://user-images.githubusercontent.com/46482115/180252031-5e46967b-7626-4a6f-bd43-9e1d1080df3e.png)

**Comment by Clemog** [comment]
Ah étrange, j'ai pas le bug de mon coté. Tu as le même problème sur le site Datagir ?

**Comment by martinregner** [comment]
Non, que là
