### ISSUE TITLE
Bug d'affichage iframe sur datagir.ademe avec Firefox

### ISSUE THREAD

**Issue by johangirod** [datagir/nosgestesclimat-site#595]
Petit bug ou l'intégration iframe est tronquée sur firefox : 

![image](https://user-images.githubusercontent.com/1775934/180718944-dd31b935-a85d-4d27-aeb1-68f9113032f8.png)

**Comment by laem** [comment]
En effet, merci @johangirod. 

On a même un très gros problème de hauteur qui s'étend sur l'écran de fin, rendant NGC inutilisable. 

Je regarde. 

https://datagir.ademe.fr/apps/nos-gestes-climat/

**Comment by laem** [comment]
Je ne sais pas pourquoi ça donne ça chez nous mais pas sur bonpote ou avenirclimatique

**Comment by laem** [comment]
Mmmh probablement car l'iframe est intégré directement et pas via un script ? 

Bon, se pose à nouveau la question de l'expérience mauvaise en iframe. Et la possibilité de fixer la hauteur du site définitivement et virer iframeresizer.

**Comment by Clemog** [comment]
Lié à https://github.com/datagir/nosgestesclimat/issues/1363 à priori

**Comment by laem** [comment]
C'est réglé :)
