### ISSUE TITLE
Bug mauvaises sous catégories

### ISSUE THREAD

**Issue by mquandalle** [datagir/nosgestesclimat-site#603]
Je ne sais pas si c'est un bug ou bien juste un problème de libellés pas clair, mais je ne comprends pas les sous-catégories suivantes :

![image](https://user-images.githubusercontent.com/1730702/185409641-b0b66760-d63d-47b5-83d0-20d361b4c7bc.png)

![image](https://user-images.githubusercontent.com/1730702/185409686-9fa4c839-9185-4fad-b6ad-854878de39f8.png)

Par ailleurs cliquer sur les trois petits points `…` de la ligne du haut ne produit aucun effet.

**Comment by laem** [comment]
Oulah ! Oui, c'est bien un gros bug. Je vais investiguer, merci :)
