### ISSUE TITLE
Intégration du nouveau logo NGC sur le site 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/nosgestesclimat-site#605]
Suite aux échanges et aux travaux de ces derniers moi nous sommes enfin parvenus à la construction d'un nouveau logo ! 
=> **Intégrer le logo au site NGC grâce aux fichiers que l'agence nous a envoyé** 

Quelques questions : 
- Le format des fichiers sont-ils compatibles pour être intégrés sur le site ?
- Couleur de la police : ils nous envoyé les logos avec une police en couleur noire. A essayer mais pas sûre que ça se marie très bien avec la Home Page actuelle => remettre la couleur de la police du logo déjà existant ? 
- Police : Ils utilisent la police NEXA. On avait tout changé pour être en Marianne : pas problématique ? (tant qu'on garde le reste du wording dans cette police) 

[CharteGraphique-NGC.pdf](https://github.com/datagir/nosgestesclimat-site/files/9394928/CharteGraphique-NGC.pdf)
[NGC_2022.zip](https://github.com/datagir/nosgestesclimat-site/files/9394929/NGC_2022.zip)

**Comment by laem** [comment]
> Police : Ils utilisent la police NEXA. On avait tout changé pour être en Marianne : pas problématique ? (tant qu'on garde le reste du wording dans cette police)

En termes de simplicité, de poids, et pour être uni avec le reste des services datagir, c'est mieux de garder Marianne je pense. 

Pour les couleurs, le nouveau logo appelle en effet des expérimentations pour voir si ça colle, si on peut faire mieux.

**Comment by Clem-mrtn** [comment]
**Nouveau format pour le logo** 
![NGC_LOGO_2022-OK](https://user-images.githubusercontent.com/76995768/188467004-d6138fbc-8d7b-4141-a668-719ea7c82462.svg)

=> bon c'est p-t trop lourd...
