### ISSUE TITLE
Bouton "recommencer" pas assez visible ?

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat-site#608]
Ordinateur W10 avec firefox

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by laem** [comment]
Je pense qu'on peut fermer cette issue. Le bouton recommencer était auparavant en première loge, et les gens cliquaient par erreur dessus. D'où le déplacement dans la page profil.
