### ISSUE TITLE
Impossible à utiliser sur version mobile 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat-site#615]
Sur Android, impossible de passer à la question suivante, dommage... 

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Je ferme au profit de #614
