### ISSUE TITLE
Bug bouton suivant sur les menus ? 

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat-site#616]
quand j'arrive aux questions alimentation, je sélectionne mes 14 menus et après je n'ai pas la main pour poursuivre : pas de bouton où cliquer pour continuer (je suis sur google chrome)

Depuis la page : `https://nosgestesclimat.fr/simulateur/bilan`

> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
Relatif à #614
