### ISSUE TITLE
Remarques sur les mosaïques

### ISSUE THREAD

**Issue by Clemog** [datagir/nosgestesclimat-site#623]
Quelques commentaires lié à #604 

- Le système actuel est imparfait : la sélection/non-sélection des cartes selon les valeurs par défaut etc.. n'est pas transparente mais presque "magique".

- Le nom du composant des mosaïques de sélection n'est oplus vraiment opportun (-> SelectDevices)

- Un peu plus important, l'option DefaultToFalse passée à ce composant SelectDevices qui permet, selon la mosaïque, d'activer la mise à "False" des éléments déjà coché, de manière visuelle d'abord puis au clic sur suivant ou sur l'une des cartes et une option activée à chaque mosaique de sélection. Je ne vois pas aujourd'hui d'exemple de mosaique de sélection qui n'utiliserait pas cette option.

- A-t-on besoin du bouton je ne sais pas pour les mosaiques "nombre" ?

**Comment by laem** [comment]
@Clemog toujours pertinent ça après tes PR sur les mosaïques ?

**Comment by Clemog** [comment]
A priori non ! Je ferme
