### ISSUE TITLE
Problème question qui n'arrive pas dans le bon ordre - Scooter / Moto

### ISSUE THREAD

**Issue by Nab-88** [datagir/nosgestesclimat-site#625]
Bonjour,

Dans la partie Transport, après avoir rempli les informations sur mon utilisation de la voiture (après la question sur la consommation moyenne de ma voiture), j'ai la question "Quel type de deux roues thermique utilisez-vous ?".
Sauf que je n'ai jamais dit posséder de deux roues thermique. Après avoir cliqué sur "Je ne sais pas" pour esquiver la question, j'ai la question "Utilisez-vous un scooter ou une moto ?".

Il y a donc un petit soucis dans l'ordre d'affichage de ces deux questions.

N'hésitez pas si vous avez besoin de plus d'infos.

**Comment by Clemog** [comment]
Hello ! merci beaucoup pour le retour ! 
Fixed by https://github.com/datagir/nosgestesclimat/commit/ea40a28caf41d5d130d78435ddca83e9250d33e7
