### ISSUE TITLE
Simplification "Comment ça marche" mode groupe

### ISSUE THREAD

**Issue by martinregner** [datagir/nosgestesclimat-site#654]
Après plusieurs tests réalisés en groupe, le pas à pas n'est pas bien compris.
Je propose de simplifier en :

1 💡 Choisissez un nom de salle
2 ⏲️ Choississez votre mode de simulation [il y a un s en trop à "choisissez" je viens de voir]
~~6~~ 3 Prêt à démarrer ?
_Une fois créé, vous pourrez partager le sondage avec un lien ou un QR code dédié à votre groupe et visualiser les résultats._
CTA _C'est parti !_

Les autres étapes (🎰 Faites toutes et tous votre simulation, 🧮 Visualisez à tout moment les résultats de votre groupe) créent de la confusion ici avec un autre CTA ("Faites votre test") qui brouille le message ; elles apparaissent une fois le sondage créé, c'est suffisant.

Qu'en pensez-vous ?

**Comment by Clem-mrtn** [comment]
Très clair 👍 
Je rejoins, ce serait chouette aussi de reprendre le tuto vidéo initialement fait par benjamin et de le faire pour le mode sondage avec ces nouvelles étapes pour mieux accompagner les utilisateurs (beaucoup de retours)

**Comment by Clemog** [comment]
A l'instant, je viens d'avoir un retour hyper intéressant qui explique pourquoi les sondages ne sont pas créés correctement !

-> L'utilisatrice a devant moi pensé "créer" le sondage en copiant le lien de partage sans aller jusqu'en bas de la page pour lancer le sondage.

Résultat: on accède bien au sondage mais il n'est pas créé dans la base de données et donc le téléchargement des données est impossible
