### ISSUE TITLE
Mesure d'impact - Questions dans le test

### ISSUE THREAD

**Issue by martinregner** [datagir/nosgestesclimat-site#655]
Pour avoir une idée, même approchée, de l'engagement des personnes à l'issue de NGC, je propose d'ajouter un autre (eh oui) petit questionnaire intégré ou sortant avec des questions du type (toutes facultative) : 

CTA : Dites nous en plus sur ce que vous avez pensez de ce test.

- Ce test vous a-t-il permis de mieux comprendre votre empreinte carbone ?
OUI tout a fait / OUI plutôt/  moyennement/ NON pas du tout
- La plus grosse surprise ou découverte a concerné : 
Le transport / le logement / L'alimentation / Le numérique / Les achats divers
- Vous pouvez précisez pourquoi si vous le souhaitez (question ouverte)
- Pensez-vous suivre une des actions proposées ou modifier certaines pratiques ? (étoile de 1 - pas du tout à 5 - fortement pour chaque secteur)
Le transport / le logement / L'alimentation / Le numérique / Les achats divers
- N'hésitez pas à nous en dire plus si vous le souhaitez (question ouverte)
- Recommanderiez-vous à vos amis ou collègues de faire ce test ? 1 à 5 étoiles
- Autre chose ? (commentaire libre)

Le questionnaire est peut-être déjà trop long... j'aurai bien demandé le niveau des actions également (en kgCO2 ou %) mais pas sûr que l'utilisateur s'en souvienne. Sinon, le degré d'effort ressenti.

Qu'en pensez-vous ?

**Comment by Clem-mrtn** [comment]
Je trouve l'idée de l'enquête intéressante pour mieux capter qualitativement la compréhension des utilisateurs NGC 
Quelques idées : 
- Attention à la taille de l'enquête, les utilisateurs auront déjà passé 10 min à répondre à 50 questions 
- En terme de timing est-ce que ce n'est pas confusant de rajouter une nouvelle enquête après celle la Home ? attendre un peu ?
- Que cherche t-on réellement à évaluer avec cette enquête ?
     - Le degré de compréhension ? : est-ce qu'il a bien compris les ordres de grandeur ? les actions ? 
     - L'engagement  ? : Est-ce qu'il veut réduire son empreinte ? est-ce qu'il a envie de s'engager dans les actions ? est-ce qu'il veut partager l'outil autour de lui ? 
     - la qualité du simulateur ? : information claire ? envie de partage ? 
     - la fidélisation ? : est-ce qu'il veut revenir ? est-ce qu'il veut être davantage accompagné ? est-ce qu'il veut être tenu au courant des nouveautés etc. ? 
- En fonction des objectifs de notre enquête, celle-ci peut prendre plusieurs formes.
**Par exemple**, si on veut évaluer la clarté du test et la bonne compréhension on pourrait plutôt envisager un petit quizz sous forme de jeu par exemple (plutôt que de sondage) à la fin pour voir si les ordres de grandeur ont été bien compris, les actions importantes bien identifiées etc.  (<=> idée de jeu avec MCCO2)

**Comment by Clem-mrtn** [comment]
J'ai quand même initié un airtable si on décide de partir sur une enquête/ sondage, on peut itérer dessus : https://airtable.com/appdsewDZTOchqILN/tblBBRLmSM5o3HapT/viwWBsB4twRuqQLUP?blocks=hide

**Comment by laem** [comment]
Je suis assez sceptique sur un tel sondage en fin de test. J'ai peur de l'énorme biais : 100% de la cohorte a déjà passé 10 minutes à répondre à 50 questions, donc a peu de chances de juger sévèrement notre site.

> Ce test vous a-t-il permis de mieux comprendre votre empreinte carbone ?

Vu l'absence de "captivité" de nos utilisateurs (personne ne les a forcés à notre connaissance), la réponse risque d'être très positive, car excluant tous les gens qui ne sont pas allés au bout. 

> La plus grosse surprise ou découverte a concerné :

Que va-t-on faire de cette réponse (qui me semble intéressante !). Je crains que la majorité des réponses dira "le numérique", étant donné notre sous-estimation documentée.

> Pensez-vous suivre une des actions proposées ou modifier certaines pratiques ? (étoile de 1 - pas du tout à 5 - fortement pour chaque secteur)

N'a-t-on pas déjà une partie la réponse dans les statistiques (catastrophiques) des sélections d'action ? Qu'allons nous faire si la moyenne est 1, si elle est 3, si elle est 4 ? 

> Recommanderiez-vous à vos amis ou collègues de faire ce test ? 1 à 5 étoiles

C'est une bonne façon de demander aux gens de noter le site je pense :+1: 

Même question : qu'allons-nous faire si la moyenne est de 1, 3, 4,  ? N'a-t-on pas déjà la réponse via le taux de partage élevé sur les RS ? Ça me semble vraiment important de parler des actions que doivent déclenchent les réponse contraintes à un formulaire.

Globalement, pourquoi ne pas plus simplement poser cette unique question (x étoiles sur 5 pour "le recommanderiez-vous") avec un champ libre "Envoyez-nous un message", et le faire au cours du test (par exemple après 20 questions, comme un intercalaire) pour capter aussi une partie des démissionnaires ? 

Autre élément important à mon avis : on avait enlevé notre champs de retour car on était submergés par des retours qui commençaient bcp trop à se ressembler : est-ce qu'on va pas se remettre dans la même situation ?

**Comment by Clemog** [comment]
> Même question : qu'allons-nous faire si la moyenne est de 1, 3, 4, ? N'a-t-on pas déjà la réponse via le taux de partage élevé sur les RS ? Ça me semble vraiment important de parler des actions que doivent déclenchent les réponse contraintes à un formulaire.
> 
> Globalement, pourquoi ne pas plus simplement poser cette unique question (x étoiles sur 5 pour "le recommanderiez-vous") avec un champ libre "Envoyez-nous un message", et le faire au cours du test (par exemple après 20 questions, comme un intercalaire) pour capter aussi une partie des démissionnaires ?

Je te rejoins sur l'après : comment analyser ces résultats et quelles actions peuvent en ressortir ?

Et je trouve très intéressant d'avoir une idée de l'évolution du taux de satisfaction plutôt que la note en elle même. Par contre je ne suis pas forcément d'accord sur le taux de partage sur les RS élevé : élevé par rapport à quoi ? quels sont nos objectifs ? Comment mesurer exactement ? (la semaine dernière le taux de clics sur partage était de 16% mais il me semble que ce ne sont pas les clics uniques, que ce n'est pas forcément sur les RS, que ça peut etre par curiosité pour le bouton ?)

**Comment by lbranaa** [comment]
Je ferme car nous avons continué les réflexions durant notre séminaire FAST, ce qui a mené aux deux questions d'impact suivantes : nosgestesclimat-site #894
