### ISSUE TITLE
NGC Groupe : Mettre en avant la fonction Sondage sur la LP

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/nosgestesclimat-site#657]
Comme discuté ensemble au séminaire, beaucoup de confusion autour des choix Sondages / Conférences
Dans une optique de simplifier le parcours utilisateur dans le mode Groupe il faudrait faire évoluer la LP NGC Groupe : 

- [x]  en mettant en avant la fonction Sondage 
- [ ] En dessous en plus petit, possibilité de choisir le mode conférence (le mettre sous forme de lien plutôt qu'une case à sélectionner par ex.)

**Comment by Clem-mrtn** [comment]
#654

**Comment by laem** [comment]
J'ai mis le mode sondage en premier, par défaut, avec un texte raccourci, et le mode conférence en 2ème avec un avertissement données surligné en jaune avec panneau ⚠️.

**Comment by lbranaa** [comment]
Je ferme car cela a été traité
