### ISSUE TITLE
Générer valeur du score mentionné dans le tuto 

### ISSUE THREAD

**Issue by Clemog** [datagir/nosgestesclimat-site#668]
J'ai ajouté directement la valeur du score dans le tuto sans le générer : https://github.com/datagir/nosgestesclimat-site/blob/b3d909fa71ac522ff4200c8f104a5aa550c377b5/source/sites/publicodes/Tutorial.tsx#L212.

Il sera nécessaire de l'intégrer dynamiquement

**Comment by laem** [comment]
J'ajoute un pb d'affichage du "?" 
![image](https://user-images.githubusercontent.com/1177762/192588768-b1b8addf-5fcd-457c-b6be-b4f97c758310.png)

**Comment by Clemog** [comment]
Je l'ai mis en `position: absolute`, c'est surement lié à ça ..

**Comment by Clemog** [comment]
Solution : utiliser DefaultFootprint

**Comment by laem** [comment]
Qui semble d'ailleurs buggué, en tout cas si c'est celui qu'on utilise dans le mode groupe, on nous a dit qu'il pouvait montrer la valeur de l'utilisateur actuel...

**Comment by Clemog** [comment]
Fixed by https://github.com/datagir/nosgestesclimat-site/commit/e56ca2c3998d2fa866e3fddce25a41645d2cef42
