### ISSUE TITLE
Mettre en place des tests automatisés simulant un utilisateur

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#674]
<meta property="og:image" content="https://user-images.githubusercontent.com/55186402/194041688-a6495607-0696-43c0-999c-5a5376f97ca1.png" />

(mael, je fais des tests)

Avant cela se faisait avec Cypress, à voir si c'est toujours l'outil adéquat. 
À voir comment l'implémenter sans gêner l'expérience de dev.

**Comment by lbranaa** [comment]
@laem, est-ce qu'il faut garder cette issue (par rapport à ce que fait @florianpanchout ?)

**Comment by laem** [comment]
La 1ère version est en ligne !
