### ISSUE TITLE
Idée de design de la page de démonstration du "modèle"

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#697]
![20221019_184414](https://user-images.githubusercontent.com/1177762/196753697-35cb7a8d-23af-4dd1-90c7-7319e4458f50.jpg)

- [ ] mettre une lettre d'information-> release

**Comment by Clemog** [comment]
Il manque seulement la release pour cette [page](https://nosgestesclimat.fr/mod%C3%A8le) ? Tu avais en tête d'autres améliorations ?

**Comment by laem** [comment]
Oui globalement la "maquette" est en ligne :) 

Après l'ambition étant quand même de faire une page plus jolie, avec quelques animations, interactions un peu bluffantes. 

Mais ça peut clairement venir dans un second temps, donc nouvelle issue.
