### ISSUE TITLE
problème de génération des résultats du sondage sur nosgestesclimat.fr

### ISSUE THREAD

**Issue by Sebastien-debeix** [datagir/nosgestesclimat-site#704]
Bonjour,
Nous avons demandé à nos collaborateurs société de remplir votre super questionnaire.
On arrive à générer un csv mais le lien : "Visualisez à tout moment les résultats de votre groupe" ne fonctionne pas pour notre société : https://nosgestesclimat.fr/sondage/Fealinx
Pouvez-vous me le transmettre ? Nous aimerions partager les résultats à l'ensemble de nos équipes
Merci par avance
Sébastien

**Comment by Clemog** [comment]
Je ferme au profit de #703, n'hésitez pas à ouvrir à nouveau !
