### ISSUE TITLE
Nos gestes climat : cours 100 éleves

### ISSUE THREAD

**Issue by lbougras** [datagir/nosgestesclimat-site#705]
Bonjour
Je vais donner plusieurs cours en amphi (100 élèves par cours) ou je vais faire un atelier Groupe Nos Gestes Climat.
Est ce que l'outil fonctionne pour des groupes de 100 élèves ?
Sincèrement,
Laurent Bougras

## Proposer une amélioration 

*Si vous avez une idée précise de votre amélioration, vous pouvez directement suivre [ce guide de contribution](https://github.com/datagir/nosgestesclimat/blob/master/CONTRIBUTING.md)*

N'hésitez pas à inclure des chiffres, des sources, des articles de presse, une ébauche de calcul par vos soins etc.

**Comment by laem** [comment]
Je me permets de fermer l'issue en attendant d'autres informations, @lbougras n'hésitez pas à répondre quand même :)
