### ISSUE TITLE
English version : review

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#708]
I'm checking the translation work on #641 to launch a good enough english version as soon as posible. Reporting the work in progress here to avoid polluting this already big PR @EmileRolley 

> This is a first check before another check by a native speaker. 

- [x] landing
- [x] tutorial
- [x] test questions, answers and descriptions
  - [x] transport
  - [x] food
  - [x] house
  - [x] others 
- [x] ending pages
- [x] action screen
- [x] changer "alert banner" : pour l'anglais, ce n'est plus une version automatique mais une beta
- [x] bad link in "This category does not depend on your answers, [read more](http://localhost:8080/documentation/services-publics)", question services publics

### What I haven't checked :
 
- all action pages and action plus pages

### What's not translated yet :

- [ ] this markdown page http://localhost:8080/pétrole-et-gaz
- [ ] the `documentation` directory of `nosgestesclimat`.
- [ ] #711

The action screens may be optional for a first launch.

**Comment by EmileRolley** [comment]
> bad link in "This category does not depend on your answers, read more", question services publics

It's working on my machine..
