### ISSUE TITLE
La récupération des résultats pose problème

### ISSUE THREAD

**Issue by Clemog** [datagir/nosgestesclimat-site#712]
Nous avons beaucoup de retours utilisateurs indiquant que le téléchargement des résultats n'est pas accessible. Souvent le pb vient du fait que le sondage n'est pas présent dans la table "survey"

**Comment by laem** [comment]
On suspecte donc que les gens ont tapé une URL de sondage avant de le créer. Question d'UX donc.

**Comment by laem** [comment]
Fixed by  #654

**Comment by Clemog** [comment]
> On suspecte donc que les gens ont tapé une URL de sondage avant de le créer. Question d'UX donc.

Il semble que c'était plutôt lié à https://github.com/datagir/nosgestesclimat-site/issues/654#issuecomment-1310130766
