### ISSUE TITLE
🐛 Bug respiration catégories

### ISSUE THREAD

**Issue by Clemog** [datagir/nosgestesclimat-site#731]
Il semble qu'il y a un bug avec les respirations des catégories mises en place dans #677 :/ (ping @laem @EmileRolley)

Elle n'apparaissent pas toujours entre les catégories, notamment la première "Transport", je me demande si ce n'est pas juste un bug au niveau de la réinitilisation du state

**Comment by EmileRolley** [comment]
Qu'est-ce qu'une _respiration_ ?

**Comment by laem** [comment]
C'est les écrans catégorie. Genre "Transport ⚙️ [Commencer]"

**Comment by laem** [comment]
Ce qui est sûr c'est qu'en fonction du state, on a en effet des comportements étranges mais non bloquants.

**Comment by laem** [comment]
Je me permets de fermer
