### ISSUE TITLE
Fix the SEO

### ISSUE THREAD

**Issue by EmileRolley** [datagir/nosgestesclimat-site#736]
NGC is currently referenced in english.

**Comment by laem** [comment]
Also problematic for preview links generated by Netlify's prerender.io

**Comment by laem** [comment]
let's keep this issue open until we see if it's fixed by my PR.

**Comment by laem** [comment]
My fix didn't work. Google doesn't understand the hreflang tag :/

![image](https://user-images.githubusercontent.com/1177762/202453241-712c9609-5e2f-46d0-bdcc-ec2e7a1a860d.png)

**Comment by laem** [comment]
Question asked on domaine dev...

**Comment by laem** [comment]
Kagi.com returns a different set of franglish mix...



![Image](https://user-images.githubusercontent.com/1177762/203288619-022ebf05-42bd-40ec-bde0-5626901e2ad4.png)

**Comment by laem** [comment]
Google a repassé la page d'accueil en anglais, et d'autres en Français. Lol. 
Bon, les effets de la PR de hier sont à attendre aujourd'hui ou demain. 
![image](https://user-images.githubusercontent.com/1177762/204746645-4e3149c2-ddc3-4f4b-9eb5-f694152bbf69.png)

**Comment by laem** [comment]
Issue fixée :)
