### ISSUE TITLE
Meta description aren't rendered

### ISSUE THREAD

**Issue by EmileRolley** [datagir/nosgestesclimat-site#742]
Meta descriptions aren't displayed anymore.

For the landing page, the `<Meta>` component is rendered two times and the second time the `description` attribute is `undefined`..

**Comment by laem** [comment]
It looks like this `t` call returns undefined for the Meta comp 

<Meta
  !···!···!···!···title={t('Connaissez-vous votre empreinte climat ?')}
  !···!···!···!···description={t('meta.publicodes.Landing.description')}
  !···!···!···!···image="https://nosgestesclimat.fr/images/dessin-nosgestesclimat.png"
  !···!···!···/>

**Comment by laem** [comment]
It works on pages like /actions, /à-propos. I don't get what doesn't work on the Landing page.

**Comment by laem** [comment]
I'm fixing it.
