### ISSUE TITLE
Améliorer le référencement des pages /actions

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#754]
We're losing all the SEO that the page action could give us, since we display the page to chose a persona for google. 

https://nosgestesclimat.fr/actions/liste

![image](https://user-images.githubusercontent.com/1177762/203274058-f729fe1b-1462-4242-af9d-35755628a908.png)

**Comment by bjlaa** [comment]
<img width="1034" alt="Capture d’écran 2023-04-27 à 16 54 23" src="https://user-images.githubusercontent.com/12382534/234902029-537cbe71-1dab-41d8-ad38-e6e535cf74ae.png">
à priori réglé ! bien que je ne sache pas comment 😄 y'a une petite typo ceci étant que je corrige.

**Comment by bjlaa** [comment]
- [ ] ajouter une page Plan de site (au passage, quick win accessibilité)
- [ ] y lister toutes les pages du site y compris les pages actions
- [ ] ajouter un lien vers cette page Plan de site dans le footer du site

**Comment by laem** [comment]
Cette issue était surtout pour exposer les fiches actions sur l'URL /action. 

Je ne connais pas la pratique du plan du site, qu'est-ce que ça apporte par rapport au sitemap ? Je vois que tu évoquais l'accessibilité, j'imagine que ça peut être une raison en soi mais c'est un sujet différent de cette issue.
