### ISSUE TITLE
Problème de téléchargement des données de sondage

### ISSUE THREAD

**Issue by StephaneGaffori** [datagir/nosgestesclimat-site#756]
Bonjour,

Le lien pour "Visualisez à tout moment les résultats de votre groupe" est inactif et je ne peux donc pas accéder aux résultats de l'étude.

**Comment by StephaneGaffori** [comment]
> Bonjour, pouvez-vous nous envoyer le lien du sondage en question ? Par exemple à contact AT nosgestesclimat.fr

Bonjour

Il s'agit de : https://nosgestesclimat.fr/sondage/ADREGIONSUDCCF

Cordialement

**Comment by laem** [comment]
@StephaneGaffori ça fonctionne pour moi, je vous montre. 

![Recording 2022-11-23 at 17 52 06](https://user-images.githubusercontent.com/1177762/203603809-5ddf060e-3fd2-45f3-885d-983e39860362.gif)

Peut-être que ça bug chez vous et pas chez moi ?

**Comment by laem** [comment]
Je ferme, faute d'infos en plus.
