### ISSUE TITLE
Modèle international "dégradé"

### ISSUE THREAD

**Issue by martinregner** [datagir/nosgestesclimat-site#766]

**Comment by martinregner** [comment]
Pour les pays qui n'ont pas encore de modèle + FE : 
- sur un URL international
- proposer une version sans valeur moyenne et donc sans "je ne sais pas" : le résultat est à la fin
- les FE du pays sont modulés via les FE de l'élec seulement en première approche (cf. réflexions déjà menée sur le sujet)

**Comment by lbranaa** [comment]
Pour une v1 du modèle international dégradé, on part après discussion sur : 
- les FE du pays sont modulés via les FE de l'élec
- On applique aux pays suivants : Royaume-Uni, Québec, Belgique, Suisse, Italie, Allemagne, Pologne, Luxembourg, Turquie + autres régions d’Outre-mer
- Ajout d’un warning pour les pays pour lesquels on ne décline pas les FE dans un premier temps : "on n’a pas de modèle qui correspond à votre pays"

**Comment by Clemog** [comment]
Je ferme au profit de #804 qui mettra en ligne une première version dégradée des pays cités dans le commentaire précédent
