### ISSUE TITLE
Release update problem

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#771]
@EmileRolley it looks like the yarn run check:releases calls a non existent file. 

It looks to me that it would suffice to just change the output of the fetch-release function to output the french source releases to the locales dir. 

Am I missing something ?

**Comment by EmileRolley** [comment]
It's weird the `check-releases.js` file dispeared :thinking: 

But, yeah it only misses to directly save the fetched releases in the `source/locale/releases/releases-fr.json` file.
