### ISSUE TITLE
Bug: personas aren't managed properly

### ISSUE THREAD

**Issue by EmileRolley** [datagir/nosgestesclimat-site#780]
## The problem

When selecting a persona, the test isn't render properly and stop on the `Quel type d'énergie utilisez-vous pour le chauffage de votre logement, eau chaude, cuisson ?` question. There are missing categories on the bottom chart bar too.

## Potential solution

The bug seems to come from the `personas.yaml` rule's names which aren't up to date with the ones in `data/`.

## Conclusion

After investigation, it was related to the computation of the `logement . chauffage` rule. Indeed, in the `personas.yaml` file we specified only the kind of heating system used with by defining the `. présent` child rule to `oui`. However, as the parent rule (e.g `logement . chauffage . fioul`) have a dependency on the `. présent` rule in their `applicable si` mechanism, all others choices need to be explicitly set to `non` in order to evaluate the `logement . chauffage` rule.

### Quick fix

To fix this issue, we simply add -- in https://github.com/datagir/nosgestesclimat/pull/1626:

```yaml
    logement . chauffage . PAC . présent: non
    logement . chauffage . fioul . présent: non
    logement . chauffage . bois . présent: non
    logement . chauffage . réseau de chaleur . présent: non
    logement . chauffage . électricité . présent: non
```

### Notes

When the `logement . chauffage . gaz . présent` is set to `oui`, we need to explicitly define the value of the `logement . chauffage . gaz . biogaz` rule.

### Remaining task

It seems that the `par défaut` mechanism doesn't have the expected behavior when used in combination with the `applicable si` or `variations` mechanisms.

**Their behaviors need to be specified in the doc.**

**Comment by Clemog** [comment]
I added some points in your comment. I think we have to think about fixing it in publicodes directly :/
