### ISSUE TITLE
Prevent the survey creation from an URL

### ISSUE THREAD

**Issue by EmileRolley** [datagir/nosgestesclimat-site#788]

**Comment by laem** [comment]
Still a problem after the UI changes of the tuto ?

**Comment by EmileRolley** [comment]
I think is should not be possible to access a survey directly from the URL if isn't already created via the form to reduce the confusion from the users which leads to recurrent issues like: #789 https://github.com/datagir/nosgestesclimat/issues/1618 https://github.com/datagir/nosgestesclimat/issues/1619
