### ISSUE TITLE
Bug d'emojis

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#792]
On dépend toujours de twemoji sur maxcdn, qui est down au moment où on l'a testé ce matin. 
Or, on était sensé maintenant reposer sur les emojis natifs ? @EmileRolley

**Comment by laem** [comment]
Il semble qu'il y ait deux catégories d'emojis dans l'implé actuelle : ceux des textes du contenu, et ceux du modèle. Ces derniers, s'ils ne sont pas remplacés par l'iconographie dédiée dans source/images/model, sont du twemoji.

**Comment by EmileRolley** [comment]
Plus généralement, il me semble que l'on avait opté pour garder les emojis natifs quand ils apparaissaient dans un texte et étaient donc considérés comme un caractères et garder ceux de twemoji pour ceux qui servent d'illustration (comme par exemple les icônes du modèle). Je ne me souviens plus si on avait acté le fait de remplacer les illustrations par des images et ne plus reposer sur des emojis ?

**Comment by laem** [comment]
Voilà la réponse pour maxcdn : https://twitter.com/mscccc/status/1612518957004513283. 
Le truc est mort.

**Comment by laem** [comment]
J'ai mis en ligne un fix :+1:  cc @Clemog 

Cela dit, je pense qu'avoir 3 façons de gérer les illustrations de ce style (twemoji, natif et illustrations dédiées pour les sujets modèle) est problématique. Sans compter la dépendance à un CDN qui peut pister l'utilisateur. 

Je renomme l'issue et je propose de la garder ouverte, pas prioritaire :)

**Comment by Clemog** [comment]
Super merci ! La solution me paraît "simple", je ne comprends pas tous les commentaires de l'issue mais je me demande si cette solution est un fix temporaire ? 
Que fait on exactement en définissant cet url dans la config ?
