### ISSUE TITLE
Refactor the documentation rendering to support compressed models

### ISSUE THREAD

**Issue by EmileRolley** [datagir/nosgestesclimat-site#799]
New compressed models introduced by #746 https://github.com/datagir/nosgestesclimat/issues/1661 will break the documentation exploration from the website. Therefore, a refactoring of the documentation rendering must be done.

A rehydratation method is experimented by @laem in #801. Note that a first version could consists to simply load the uncompressed model when visiting the documentation pages.

**Comment by laem** [comment]
As explained in #801, going with Next is the best solution performance-wise, but not a short term solution for this compression work. 

I think going with #778 but with the uncompressed model is the best compromise :)

**Comment by EmileRolley** [comment]
Done by #806
