### ISSUE TITLE
Rassurer sur la vie privée en cas de partage du résultat

### ISSUE THREAD

**Issue by Seb35** [datagir/nosgestesclimat-site#80]
Hello, j’ai testé le simulateur suite au [tweets](https://twitter.com/maeool/status/1287365960098361345) de @laem.

À la fin, il est proposé de partager les résultats via un lien, par exemple https://ecolab.ademe.fr/apps/climat/fin?total=4463&details=a1.45s1.28l0.83t0.67b0.13n0.07f0.03. Je me suis posé la question de l’étendue du partage : est-ce que ça partage tous les résultats (montant de l’épargne, régime alimentaire, etc) ou juste les résultats ?

Après analyse de l’URL et après l’avoir mise dans une fenêtre privée, je comprend que **seul le résultat global et son découpage en grandes catégories est partagé**. Mais il serait souhaitable de mettre une petite phrase pour informer et rassurer les utilisateurs moins techniques.

**Comment by Seb35** [comment]
Un tel message serait à mettre [à cet endroit je crois](https://github.com/betagouv/ecolab-climat/blob/master/source/sites/publicodes/Fin.js#L140-L148), mais je ne suis pas forcément très avisé en UX.

Cf aussi #33 même si ce n’est pas exactement la même chose.

**Comment by Seb35** [comment]
En fait, à la réflexion, le découpage en grandes catégories peut quand même donner pas mal d’indications sur la vie privée :
* en alimentation : le fait que l’on mange de la viande régulièrement est le plus gros poste de dépense en CO2 et donc ça se voit : 1t pour la viande une fois par semaine ; les autres postes sont plus faibles et d’ordre de grandeur similaire (200 à 500 kg selon les paramètres)
* en finance : il n’y a que 2 questions, et il est peu probable que les gens mélangent beaucoup entre la finance classique et la finance responsable, donc on peut en déduire assez facilement le niveau d’épargne ou au moins une bonne estimation
* en transport : l’avion longue distance est très visible bien sûr

Bref, le découpage en grandes catégories permet de dévoiler une partie des habitudes et du niveau de vie de façon un peu fine, et donc peut-être que ça peut gêner certaines personnes. Si on répond oui à cette question, ça peut s’aménager en ayant *une option pour ne partager que le niveau global ou le détail en grandes catégories*. Bien sûr le niveau global donne déjà une certaine indication du niveau de vie. À grande échelle, j’imagine que le niveau de partage peut dépendre en partie de ce niveau de vie privée partagé.

**Comment by laem** [comment]
Bonjour ! Super, merci pour ces réflexions. Je ne m'étais en effet pas aperçu que le partage du résultat révèle l'épargne de l'utilisateur 😅 entre autres. 
Je ne suis pas pour complexifier le bouton de partage avec 2 choix (si l'utilisateur veut seulement partager son score final, il est libre de le faire comme ça : "j'ai fait 8 tonnes, et vous ? ecolab.ademe.fr/apps/climat"), mais plutôt pour un petit texte qui explique que le bouton partage seulement le contenu affiché sur la page affichée à l'écran.
