### ISSUE TITLE
#Meilleure visibilité des guides de l'animateur 

### ISSUE THREAD

**Issue by Benjamin-Boisserie-ABC** [datagir/nosgestesclimat-site#802]
J'ai deux échanges avec des acteurs qui réutilisent massivement NGC et son contenu pédagogique et aucun des deux n'avait connaissance des guides de l'animateur. 

Ces derniers ne sont d'ailleurs même pas visibles comme une étape lors de la sélection "Mode Sondage" ou "Mode Conférence" car il faut d'abord lancer son sondage pour voir sur le bas de la page suivante un lien renvoyant vers une explication de la différence entre sondage et conférence. En scrollant sur le bas de cette page on arrive aux liens vers les guides

Ne faudrait-il pas leur donner une meilleure visibilité ?

**Comment by Clemog** [comment]
Yes, c'est noté dans #793 ! Je ferme du coup et je note l'issue dans la meta.
