### ISSUE TITLE
Bug espace à la fin du nom de sondage

### ISSUE THREAD

**Issue by Clemog** [datagir/nosgestesclimat-site#814]
Nous avons des retours récurrents sur la création de sondages infructueuse.

Une première chose facile à corriger : trimmer l'espace à la fin de l'input du nom du sondage

**Comment by laem** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim

**Comment by laem** [comment]
C'est réglé par #818
