### ISSUE TITLE
Simplification page pour les personnes invitées dans un sondage

### ISSUE THREAD

**Issue by lbranaa** [datagir/nosgestesclimat-site#819]
Dans le cas où on envoie le lien d'un sondage à un participant, il tombe sur une page avec beaucoup d'infos, qui ne sont pas forcément pertinentes pour lui et peuvent perturber la compréhension.
Il y a notamment un autre bouton "Faites toutes et tous votre simulation" (les participants cliquant sur ce lien sont-ils comptabilisés dans le groupe du sondage ?)

![Capture d’écran 2023-01-30 à 18 22 37](https://user-images.githubusercontent.com/120486950/215548877-2dcae296-dff9-4b57-8f74-e2b363511b9f.png)
![Capture d’écran 2023-01-30 à 18 23 44](https://user-images.githubusercontent.com/120486950/215549122-5a9bddf0-388c-4cd3-b11e-ad1904875dcf.png)

**Comment by laem** [comment]
En testant on se rend compte que ce n'est pas non plus évident pour les gens qui ont déjà un test en mémoire : il faudrait les avertir qu'il sera automatiquement intégré dans le sondage, et dire que le bouton recommencer existe.
