### ISSUE TITLE
Expliquer rapidement le principe du graphique du mode groupe

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#823]
Du genre "chaque point représente un participants"

**Comment by lbranaa** [comment]
Petite typo - "bare" --> "barre" (je n'ai pas réussi à le modifier directement) @laem 
![Capture d’écran 2023-02-06 à 11 01 28](https://user-images.githubusercontent.com/120486950/216943593-9c037956-20d0-4e8f-8b91-50e13b65f75e.png)

**Comment by laem** [comment]
OK, pris en compte dans la nouvelle PR.
