### ISSUE TITLE
Mieux introduire les explications des calculs sur les pages de documentation 

### ISSUE THREAD

**Issue by QuentinBrch** [datagir/nosgestesclimat-site#83]
La partie “Calcul” et “Somme” fait un peu trop “langage interne” et mériterait d'être pensé autrement dans le parcours utilisateur. On pourrait par exemple, mettre un titre comme : “Que contient le poste “alimentation” ?” ou “Allons dans le détail de l’alimentation”. 

On retrouve aussi parfois les mêmes pages dans les liens internes des parties “calcul” et “page associée”, ce qui n'est pas forcement pertinent.

**Comment by laem** [comment]
Très bonnes remarques. Malheureusement, c'est au niveau de la bibliothèque publi.codes qu'il faut agir, c'est un peu plus compliqué que de changer les textes du modèle. 

Voir #6

**Comment by laem** [comment]
Je ferme car les choses ont bien changé depuis, mais #484 et les tickets liés sont toujours là.
