### ISSUE TITLE
Page blanche sur la page profil au clic sur le bouton déroulant "voiture" (transports)

### ISSUE THREAD

**Issue by Picorims** [datagir/nosgestesclimat-site#837]
![image](https://user-images.githubusercontent.com/41078963/218316103-2abdbe5a-1547-4f09-9f6f-0f8bc873ff0d.png)

En cliquant sur le bouton déroulant "voiture", dans le conteneur dépliable "transport", la page devient blanche. Les erreurs suivantes s'affichent dans la console web :

![image](https://user-images.githubusercontent.com/41078963/218316272-5732a872-225b-40d0-a7be-ec9b6eb47d22.png)

- Le test a été complété à 100%.
- L'aide à la saisie pour la distance en voiture a été utilisée (avec le champ label facultatif laissé vide).
- Les informations ont été saisies en tant que non propriétaire du véhicule.
- Le problème se produit avec ou sans la participation à un sondage (j'ai rencontré le problème dans les deux cas avec un parcours très similaire).

A noter que retrouver sa progression une fois dans cet état est assez peu intuitive pour l'utilisateur, car rafraîchir la page (premier réflexe de mon côté) l'efface. Cependant, ouvrir la page dans un nouvel onglet sans fermer la précédente permet de retrouver sa progression (donc le bug serait probablement dans le rendu de l'interface).

**Comment by EmileRolley** [comment]
Le problème a été corrigé par @mlbiche dans #835 :)
