### ISSUE TITLE
Erreurs 404 pour certaines règles de la doc

### ISSUE THREAD

**Issue by Clemog** [datagir/nosgestesclimat-site#841]
Le problème apparaît pour toutes les pages de documentation correspondantes à une règle vide : 

https://github.com/datagir/nosgestesclimat-site/blob/3a0e775737e20e0f812fdde779d24082a60f3d50/source/sites/publicodes/pages/Documentation.tsx#L48-L52

## Proposition

Il faudrait travailler la page rendu, affichant par exemple les _pages proches_.

**Comment by EmileRolley** [comment]
La page 404 apparaît lorsque l'on essaie d'afficher la page d'une règles vide.

**Comment by Clemog** [comment]
@EmileRolley j'ai l'impression que se pose la question de pourquoi ces règles sont affichées dans le menu ? Est qu'est ce qu'on aimerait voir dans ce menu pour qu'il soit plus facile de naviguer dans la documentation

**Comment by laem** [comment]
Tu as un exemple de règle vide ainsi ?

**Comment by Clemog** [comment]
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/55186402/222371185-82c24f38-6135-43f4-bc2b-431817b3fb4a.png">
Au clic sur 'TER' ici :) (https://nosgestesclimat.fr/documentation/transport/TER)

**Comment by Clemog** [comment]
J'ai ouvert une nouvelle issue côté modèle (https://github.com/datagir/nosgestesclimat/issues), je pense qu'il faut qu'on revienne sur ce bug

**Comment by Clemog** [comment]
A nouveau le problème ici en cliquant sur ratio : https://nosgestesclimat.fr/documentation/empreinte-branche/S96-par-hab/services-marchands

La règle étant définie dans un `avec` sans attribut (valeur seule)
