### ISSUE TITLE
Si /geolocation ne détecte pas de pays

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#846]
Normalement, le bug initial est résolu ✅ :

> - Dans la page profil
> 
> > Nous avons détecté que vous faites cette simulation depuis .Pour le moment, il n'existe pas de modèle de calcul pour {{countryName}}, le modèle Français vous est proposé par défaut.
> 
> - dans l'avertissement 
> ![image](https://user-images.githubusercontent.com/1177762/220167582-e0ea21b5-0778-49f3-9e53-def7de1f912f.png)

Néanmoins, 2 petites modifs peuvent être intéressantes :

- [ ] Afficher le message de "non détection" de la région en bandeau
- [ ] Faire en sorte (si possible) de rendre plus propre l'implé du bandeau et du message de localisation dans "Profil " en harmonisant les textes notamment

**Comment by Clemog** [comment]
Je n'arrive pas à reproduire le bug ?

**Comment by laem** [comment]
C'était via Opera VPN gratuit je crois.

**Comment by Clemog** [comment]
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/55186402/221605402-ed72d571-e388-4a7a-bd07-3a9983c032f5.png">

En local j'ai pas le bug ..

D'ailleurs, ce serait pas mal d'ajouter un message dans le bandeau quand la détection échoue et faire en sorte de mutualiser les 2 messages (dans profil et dans le bandeau) pour éviter les ducplications

**Comment by laem** [comment]
Je confirme que je n'ai plus ce problème. Je pense qu'on peut le fermer en gardant en tête qu'il reviendra peut-être par une autre porte un jour. 
![image](https://user-images.githubusercontent.com/1177762/223432924-085b3626-e183-4294-ab4d-e54eca648a2f.png)

**Comment by Clemog** [comment]
Il y a besoin de mettre une pop up? Je ne crois pas qu'il y en ait actuellement

**Comment by Clemog** [comment]
Yes carrément ! Et j'avais noté d'essayer de mutualiser le texte de la page profil et de la popup éventuellement :)

**Comment by Clemog** [comment]
Fixed by https://github.com/datagir/nosgestesclimat-site/pull/893
