### ISSUE TITLE
Bug intégration iFrame.js

### ISSUE THREAD

**Issue by BenFdesign** [datagir/nosgestesclimat-site#850]
Bonjour,

Je n'ai rien vu là dessus sur le git :
J'ai un bug d'affichage de l'iFrame NGC, intégré dans un .html suivant la méthode [que vous proposez ici](https://codesandbox.io/s/angry-rhodes-hu8ct?file=/index.html).

Le contenu de l'iframe semble s'étendre à l'infini, ce qui rend impossible jusque l'accès au bouton "Faire le test" (le contenu du frame "fuit" la souris et se recalibre indéfiniment). En passant sur un affichage mobile, j'ai réussi à avancer un peu plus dans les questions, mais je me suis retrouvé bloqué à la question "Textiles" (bas de page blanc et tronqué, le bouton _question suivante_ ne s'affiche pas).
Le bug est présent sur Mozilla 110.0 (64 bits), et sur Chrome 110.0.5481.104.
Il n'apparaît pas sur codesandbox.
Tweeker le css pour rendre le défilement impossible n'a pas fonctionné à la hauteur de mes connaissances

À terme, mon objectif sera d'intégrer NGC dans l'iFrame d'un site associatif pour diffuser la comptabilité carbone dans des lieux d'intervention tout en récupérant automatiquement et anonymement les résultats par secteur, dans une base de données personnelle. Aussi, je ne peux pas me passer de la balise data-share-data="true", je ne sais pas si celle-ci fonctionnerait avec un iframe classique.

Voici le script d'intégration que j'utilise :
`<script
id="nosgestesclimat"
src="https://nosgestesclimat.fr/iframe.js"
data-share-data="true">
</script>`

Bonne journée !

Benjamin

**Comment by laem** [comment]
Très liée à https://github.com/datagir/nosgestesclimat-site/issues/663

**Comment by BenFdesign** [comment]
Première solution trouvée en intégrant l'iframe sans passer par le script _ngc.fr/iframe.js_, qui ajoute automatiquement l'id _iFrameResizer0_ (qui semble être responsable du _height_ qui s'étire à l'infini).

Maintenant, c'est plus des problématiques de responsivité sur mobile (le calculateur reste par exemple en mode 16/9 sur mobile, il faut réduire énormément avant d'avoir la version réduite sans les catégories "Le test, agir, mon profil" sur le côté). Ca ne me dérange pas pour l'instant, je pourrai trouver des solutions en bricolant.

Dans tous les cas, une solution d'iframe avec un resize automatique qui fonctionne bien pourra sans doute aider beaucoup de monde à intégrer votre supercalculateur :)

Merci pour votre super travail !
Ben

```
<iframe
      src="https://nosgestesclimat.fr/?iframe&integratorUrl=file%3A%2F%2F%2FD%3A%2F0-%2520RQeT%2FLabo%2FComptaCarboneV1%2Fsrc%2Findex.html&shareData=true"
      style="border: medium none;
            width: 100%;
            display: block;
            margin: 10px auto;
            min-height: 700px;
            overflow: hidden;
            height: 800px;"
      allowfullscreen="true"
      webkitallowfullscreen="true"
      mozallowfullscreen="true"
      scrolling="no">
</iframe>
```

**Comment by BenFdesign** [comment]
Ah, je viens de voir le précédent message. C'est parfait, merci beaucoup !

**Comment by laem** [comment]
> il semblerait que la méthode ci-dessous ne permette pas d'envoyer les résultats vers la console. J'attends donc vos mises à jour sur l'iframe fixé

MMMh a priori si, tant que l'option "shareData=true" est dans l'URL à la fin du test. 

J'ai mis en ligne la version corrigée, qui assume maintenant une taille fixe. Qu'en penses-tu ?

**Comment by BenFdesign** [comment]
Une erreur de ma part alors sans doute, pour la tentative avec la balise <iframe>.

Je suis repassé sur l'appel de l'iframe par script et la nouvelle version est super, tout fonctionne, et ça rend très bien !

Le seul inconvénient (très minime) en expérience utilisateur, c'est le placement du bouton _"AUCUN"_ dans les questions textiles et électroménager. Étant placé en haut, si on a rien à cocher, il faut aller tout en bas puis remonter puis redescendre. L'expérience serait plus fluide si le bouton était en bas, à côté ou au dessus de _"question suivante"_. Comme la fenêtre est réduite dans cette version, on peut avoir l'impression qu'on est "bloqué" dans la question. Mais rien de grave.

Super travail, merci à vous !
Ben

PS : Je vais joindre un codesandbox de ma version pour récupérer les résultats sur un Firebase, ça pourra surement servir à d'autres.

**Comment by laem** [comment]
Merci, j'en fais une issue : https://github.com/datagir/nosgestesclimat-site/issues/865

Merci pour les encouragements, et super pour le codesandbox :)

**Comment by BenFdesign** [comment]
Le sandbox pour récupération des résultats sur Firebase realtime database :
https://codesandbox.io/s/template-resultats-ngc-vers-firebase-u1pkcv
