### ISSUE TITLE
Rajout d'une entrée "mode groupe" dans le menu de gauche

### ISSUE THREAD

**Issue by lbranaa** [datagir/nosgestesclimat-site#858]
A la suite d'un atelier avec la designer Laura, nous proposons d'améliorer la navigation du mode groupe. Aujourd'hui, il est difficile pour l'utilisateur d'accéder au mode groupe à partir d'un autre endroit que la page d'accueil. Nous proposons donc de rajouter dans le menu de gauche une entrée "Mode groupe", sur laquelle on puisse aller à n'importe quel moment.

Il sera ensuite intéressant de voir si plus de personnes utilisent le mode groupe avec cette nouvelle entrée dans le menu.

**Comment by laem** [comment]
Je me rends compte que c'est pas si simple : l'entrée permanente dans le menu doit-elle rediriger vers /groupe ou vers la conférence dans le cas où une conérence est en cours pour cet utilisateur ? Idem pour sondage. 

Le bouton sur l'accueil lui reirige vers /groupe. L'entrée du menu, qui s'affiche qu'en cas de mode groupe actif, redirige vers le mode groupe en question, qui sont deux pages bien distinctes.

**Comment by laem** [comment]
Globalement ce n'est pas une bonne pratique de donner des cibles différentes à un même lien dans un menu.

**Comment by laem** [comment]
Le mieux me semble être que l'entrée du menu redirige toujours vers /groupe, mais que l'indicateur mentionné ici https://github.com/datagir/nosgestesclimat-site/issues/860 soit le moyen de revenir vers la page de conf active.

**Comment by lbranaa** [comment]
Effectivement, pour moi l'idée était que ce bouton te ramène à /groupe si tu n'es pas en mode groupe, et si tu as déjà activé le mode conférence ou sondage, que ça te ramène sur la page des résultats. 
Pourquoi ce n'est pas une bonne pratique ?

**Comment by laem** [comment]
Par exemple, un utilisateur clique sur l'entrée du menu groupe, il voit la page de lancement de mode groupe. Il choisit une conférence. Il se rend compte qu'il n'a pas bien lu les instructions, ou qu'il s'est peut-être trompé sur conf/sondage -> il veut revenir en arrière. Mais alors, le menu ne lui permet plus de revenir sur la page qu'il a vue.
