### ISSUE TITLE
Mise en avant dans le menu de la concomitance "mode groupe" et "le test"

### ISSUE THREAD

**Issue by lbranaa** [datagir/nosgestesclimat-site#859]
A la suite d'un atelier avec la designer Laura, nous proposons d'améliorer la navigation du mode groupe. Aujourd'hui, il est difficile pour l'utilisateur de comprendre qu'il est à la fois en train de faire le test et dans le mode groupe. 
Nous proposons donc :

- [ ] de mettre en avant uniquement le nom du test (et non pas l'entrée "Mode groupe"), en le réduisant pour qu'il ne soit pas trop gros par rapport au reste. 

- [ ] d'encadrer l'entrée "Le test" du menu

Voir la maquette de Laura : 

![Capture d’écran 2023-02-23 à 16 10 58](https://user-images.githubusercontent.com/120486950/220947176-1f44df94-1831-4901-9da0-9ac747b9b94d.png)

**Comment by laem** [comment]
Fait, avec une variation : la salle de test est dans un bandeau en haut, qui est compatible mobile, plutôt que dans le menu.
