### ISSUE TITLE
Ajout d'un fil d'Ariane pour le mode groupe pendant le test

### ISSUE THREAD

**Issue by lbranaa** [datagir/nosgestesclimat-site#860]
A la suite d'un atelier avec la designer Laura, nous proposons d'améliorer la navigation du mode groupe. Aujourd'hui, il est difficile pour l'utilisateur de savoir comment revenir aux résultats du mode groupe quand on fait le test / quand on l'a fini.
Nous proposons donc de rajouter un fil d'Ariane dans les pages du test en mode groupe : "Revenir aux résultats du groupe".

Voir la maquette de Laura :
![Capture d’écran 2023-02-23 à 16 10 58](https://user-images.githubusercontent.com/120486950/220948930-50f4d101-12ab-40ad-9c3a-71a377313af9.png)

**Comment by laem** [comment]
Fait sous forme de bandeau bien visible en haut de la page, qui au clic ramène sur la salle de mode groupe.
