### ISSUE TITLE
Ajout d'un choix pour l'utilisateur d'utiliser ou non son précédent résultat de test dans un sondage

### ISSUE THREAD

**Issue by lbranaa** [datagir/nosgestesclimat-site#861]
Aujourd'hui, les utilisateurs qui arrivent sur un lien de sondage et ont déjà fait un test auparavant voient leur test directement intégré dans les résultats du sondage. Nous souhaiterions pouvoir laisser le choix à l'utilisateur d'intégrer ou non les résultats précédents au sondage.

- [ ] Sur la page d'invitation au sondage, rajouter une check box "Si j’ai déjà fait le test précédemment, je souhaite que les résultats soient utilisés pour ce sondage".
- [ ] Si la personne souhaite le rajouter, prendre en compte ses résultats précédents ; sinon, ne pas les prendre en compte

**Comment by laem** [comment]
Je réfléchis à commenter implémenter ça. 

Soit on (A) implémente une gestion du multi-simulations, mais ça demande du temps. À creuser, je sais pas trop dire là rapidement. 

Sinon, c'est pas si simple. Car l'utilisateur qui cliquerait "non je ne souhaite pas réutiliser mon ancien test", en l'état actuel de notre gestion des simulations, se verrait supprimer son ancienne simulation. 

Donc le plus simple serait de mettre un bouton "supprimer ma simulation actuelle pour la refaire pour le sondage", mais en termes d'UX c'est violent je trouve, ça peut être mal compris. 

Ça rejoint d'ailleurs le problème des personas affichés en début de parcours d'action quand la simulation n'est pas terminée : un clic supprime la situation actuelle de l'utilisateur, sans possibilité de revenir en arrière. 

L'autre possibilité, serait qu'on archive la simulation s'il coche pas la case, mais qu'elle reste accessible sur la page profil par exemple. Mais finalement ça revient à implémenter A), c'est même une façon habile de le faire sans tout casser.

**Comment by laem** [comment]
En termes d'UX, la question se pose alors si on veut : 

- continuer à charger automatiquement la dernière simulation pour l'utilisateur, avec le risque non évalué mais à mon avis bien présent que l'utilisateur ne comprenne pas pourquoi il a déjà un test terminé ou partiellement terminé
- ne faire que lui proposer de récupérer sa dernière simulation via un bouton bien évident

Le choix 2) résoudrait le problème mode groupe / enquête : par défaut, sans action, l'utilisateur partira toujours d'un test vide. 

2) pose problème quand on fait un F5. Nous en tant que développeurs de NGC, ça nous arrive très souvent. Pour l'utilisateur, pas vraiment. Mais quand même. 

En pratique, le mieux me semble donc être d'adopter un comportement hybride, comme pour les sessions de compte tradi : en fonction de la date de la dernière simulation, on la charge automatiquement si elle est récente, et pas si elle est expirée (par exemple, expiration 24h après la dernière activité).
