### ISSUE TITLE
Bandeau warning version beta à faire "repoper" si réouverture du test

### ISSUE THREAD

**Issue by lbranaa** [datagir/nosgestesclimat-site#862]
Pour les versions du modèle autres que la France métropolitaine, un bandeau est intégré pour avertir que le modèle est en version beta. Il est possible de fermer ce bandeau. Or, quand on a fermé le bandeau une fois, il ne se réouvre plus si on se reconnecte une nouvelle fois.

- [x] Faire en sorte que le bandeau "repope" si on réouvre la page, même si on a fermé le bandeau une première fois
- [x] Typo : écrire "la vôtre" au lieu de "la votre" dans le bandeau

![Capture d’écran 2023-02-23 à 17 28 22](https://user-images.githubusercontent.com/120486950/220969252-128b43b1-91b3-47be-8b17-8182856f3df0.png)

**Comment by laem** [comment]
C'est fait dans #866.
