### ISSUE TITLE
Mise en place de tests e2e sur le site

### ISSUE THREAD

**Issue by lbranaa** [datagir/nosgestesclimat-site#872]
L'objectif est de mettre en place des tests qui permettent de simuler un comportement humain sur le site : 

- [ ] Vérifier que les personas peuvent tous compléter le test et obtenir le bon total
- [ ] Parcourir l'ensemble du sitemap et s'assurer que toutes les pages contiennent du html (et non pas une page blanche)

**Comment by lbranaa** [comment]
@dxb @laem on en est où là-dessus ?

**Comment by dxb** [comment]
Je me suis remis dessus ce matin... Il y'a un truc qui coince avec les personas. Sinon, les autres tests fonctionnent.

**Comment by florianpanchout** [comment]
@dxb On peut en discuter si tu veux. Le test des personas ne fonctionne pas car je n'arrive pas à lancer (ou en tout cas à joindre) le serveur de dev du modèle.

Je pense qu'à terme il faut de toute façon que les tests se fassent sur le serveur de prod (et pas de dev). Je pensais que ça me ferait gagner du temps pour une v1 mais visiblement non

**Comment by dxb** [comment]
@florianpanchout j'ai ré-activé le test, avec une url de prod pour aller chercher les personnas.
Cela fonctionne, mais le test prends plus de 4 minutes sur mon poste.
https://github.com/datagir/nosgestesclimat-site/pull/901/commits/c93b8b1c1a9c8d3883d2c69cfc9a9d8ad680a6ff
