### ISSUE TITLE
Tester la mise en place d'une alternative à Matomo - Plausible

### ISSUE THREAD

**Issue by lbranaa** [datagir/nosgestesclimat-site#895]
Au vu des limitations de Matomo aujourd'hui pour sortir les statistiques dont nous avons besoin, nous souhaitons tester d'autres outils. L'objectif de cette issue est de déployer le test avec Plausible

**Comment by laem** [comment]
Notamment, une alternative qui nous permet d'utiliser la fonctionnalité que Matomo appelle "dimension" (un événement attaché à l'utilisateur, qui ne se reproduit pas en doublon), qui est très limitée. 

Un outil qui nous permet de tester des hypothèses *en live* (ou avec un temps de processing < 1 mi) dans les réunions. Ce que ne nous permet pas Matomo, car ses funnels sont hyper lents à calculer.

**Comment by laem** [comment]
Autre problème sur l'API : Matomo est assez nul dans sa doc, et l'API est limitée à 500 éléments (pages par exemple) par requête. En bref, on n'a pas un accès total pour faire les stats détaillées qu'on veut.

**Comment by laem** [comment]
Une chose importante : on peut tester très facilement une alternative. On la connecte, on récolte les analytics pour 1j, on test éventuellement l'implé d'une mesure d'événement.

**Comment by dxb** [comment]
> Notamment, une alternative qui nous permet d'utiliser la fonctionnalité que Matomo appelle "dimension" (un événement attaché à l'utilisateur, qui ne se reproduit pas en doublon), qui est très limitée.
> 
> Un outil qui nous permet de tester des hypothèses _en live_ (ou avec un temps de processing < 1 mi) dans les réunions. Ce que ne nous permet pas Matomo, car ses funnels sont hyper lents à calculer.

Il y'a une issue qui décrit en détail ce besoin ? 
Les objectifs ne peuvent être utilisés pour ça ? 
Les dimensions sont identifiées de quelle façon ?
Les "rapports" de matomo, sont soit générés par une tache cron, soit à la demande lors de l'affichage. Mais effectivement, on est pas vraiment dans de l'analyse temps réel à la mili-seconde.

**Comment by laem** [comment]
Les objectifs sont intéressants, mais peu puissants : par exemple, on a l'objectif "a terminé la simulation", mais on ne peut pas combiner deux événements pour éviter l'écueil de l'iframe (les iframes nous pourissent nos stats avec des visites fantômes). Il nous faudrait "a terminé la simulation" && "a commencé la simulation". 

![Uploading image.png…]()

Cette issue est à rapprocher du besoin précis de https://github.com/datagir/nosgestesclimat-site/pull/907. 
On veut stocker l'éventuelle réponse de l'utilisateur à notre étude d'impact sur deux questions numériques, plus éventuellement un champs libre. Les `événements` Matomo ont des problèmes : difficile de créer des segments d'utilisateurs ayant par exemple répondu > 4 à la question "vous avez appris quelque chose" && ayant terminé le test, car il faut les préparer à l'avance et attendre qu'ils soient calculés. On ne pourra pas non plus travailler sur la distribution de réponse à ces questions, du fait de l'API limitée (les 500 pages), ce n'est pas une bonne base de données.

**Comment by laem** [comment]
À investiguer : plusieurs collègues de beta nous disent qu'ils sont passés à Plausible https://plausible.io/docs/goal-conversions

**Comment by dxb** [comment]
J'ai donc fait un test en local avec Plausible https://github.com/datagir/nosgestesclimat-site/pull/947
Sa simplicité entraine quelques limitations.
Je pense que se sera à vous de trancher après l'expérimentation.

Prochaines étapes :
Ouvrir un compte et lancer le test en prod, on a 30 jours pour essayer.

Alternative : On peut l'auto-héberger, mais ça n'est peut être pas nécéssaire.
