### ISSUE TITLE
Mettre en place une landing international

### ISSUE THREAD

**Issue by lbranaa** [datagir/nosgestesclimat-site#897]
Objectif : faire de la communication sur les versions des modèles internationaux
https://github.com/datagir/nosgestesclimat/pull/1732

- Ajouter qques stats i18n sur cette page ?

**Comment by Clemog** [comment]
Vu avec @jeremiecook 

Une première idée pourrait être simplement l'ajout d'un paragraphe https://nosgestesclimat.fr/modèle

On pourrait je pense facilement générer autant de pages de que de régions mais pour quoi ? pour qui ?

**Comment by lbranaa** [comment]
V1 réalisé avec #908, suite des évolutions avec #936
