### ISSUE TITLE
Lister toutes les questions du test, pour nos partenaires

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#898]
![Recording 2023-03-14 at 11 54 17](https://user-images.githubusercontent.com/1177762/224979759-e3a8e002-591a-4164-b13e-905153865ac9.gif)

Implémenté sur #885

**Comment by lbranaa** [comment]
On peut fermer, c'est fait, non ?

**Comment by laem** [comment]
Je préfère garder ouverte tant que 885 n'est pas mergée.
