### ISSUE TITLE
static build - génération d'une version statique

### ISSUE THREAD

**Issue by simogeo** [datagir/nosgestesclimat-site#915]
Bonjour,

Je cherche à génerer un build static de nosgestesclimat. Je ne vois pas de script build ...

Le fichier package.json propose une commande compile que je viens de tester et qui ne me semble pas vraiment opérationnelle.

(Je suis Simon avec qui vous avez échangé il y a quelques mois au sujet de la déclinaison polyénsienne de NGC)

Merci de votre retour,

**Comment by simogeo** [comment]
Pour être plus clair,

Les fichiers sont bien générés mais j'obtiens des erreurs de paths

Je peux changer la balise <base> dans le index.html généré pour les réparer. Toutefois, j'observe encore 3 erreurs :

```
XHRGEThttps://ecolab-data.netlify.app/co2.json
[HTTP/2 404 Not Found 169ms]
```

`SW registration failed:  TypeError: ServiceWorker script at http://localhost/sw.js for scope http://localhost/ encountered an error during installation. Provider.tsx:32:16`

` Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

**Comment by laem** [comment]
Bonjour @simogeo. As-tu bien suivi les instructions de ce paragraphe ? https://github.com/datagir/nosgestesclimat-site#installation

nosgestesclimat-site ne fonctionne pas sans datagir/nosgestesclimat :) 

D'autre part, l'URL des données du modèle (le modèle c'est datagir/nosgestesclimat) n'est pas (encore) paramétrée, donc redirige pars défaut sur http://data.nosgestesclimat.fr/*

**Comment by simogeo** [comment]
Hello @laem et merci pour ton retour. 
Je suis bien en mesure de faire tourner une instance de nosgestesclimat-site avec les données nosgestesclimat en développement avec yarn en local.

Je souhaiterais juste être en mesure de faire un build statique pour l'héberger en prod.

Comment faites-vous de votre côté ? vous héberger chez netlify, sans faire de build ?

**Comment by laem** [comment]
> Comment faites-vous de votre côté ? vous hébergez chez netlify, sans faire de build ?

Oui chez Netlify, et c'est la commande yarn compile qui fait le build

**Comment by simogeo** [comment]
Merci @laem et désolé du retour tardif. J'étais pris par ailleurs mais souhaite investir le sujet NGC ces jours-ci.
Y a t'il une doc quelque part pour configurer les commandes de build ? 

Je souhaiterai faire un build static pour hébergement chez OVH

**Comment by laem** [comment]
>  Y a t'il une doc quelque part pour configurer les commandes de build ?

Est-ce que tu as besoin de plus que le package.json et les ficheirs qu'il référence ?

**Comment by simogeo** [comment]
@laem : apparemment oui , puisque j'obtiens les erreurs mentionnées ici : https://github.com/datagir/nosgestesclimat-site/issues/915#issuecomment-1492184522

Pour info, je n'utilise pas tout à fait la dernière version de [nosgestesclimat-site](https://github.com/datagir/nosgestesclimat-site) mais une version qui est [antérieure à l'intégration du modèle de données comme submodule](https://github.com/datagir/nosgestesclimat-site/commit/5c841ea961e5ae69b59cf789ef719ee715ef3cdf)  

Je souhaiterai rester sur cette version qui ne tient pas compte de l'i18n et dispose des personae

**Comment by laem** [comment]
Ah ! Malheureusement je crois que ça va être compliqué de maintenir une version si ancienne. Quelle lest la raison ?

**Comment by simogeo** [comment]
@laem : j'ai fait toutes les modifs nécessaires et ça tourne. 

Dans une optique d'essaimage de l'outil, il serait intéressant d'externaliser certaines variables dans un fichier de configuration - elles sont aujourd'hui hardcodées. Ce qui je trouve, ne facilite pas la prise en main, d'autant plus qu'aucune documentation n'y fait référence.

Merci pour le retour
