### ISSUE TITLE
Les boutons "i" et "?" devraient être des tooltip ou des modales

### ISSUE THREAD

**Issue by bjlaa** [datagir/nosgestesclimat-site#923]
Actuellement les boutons info et aide ajoute un enfant dans le DOM, ce qui décale tous les éléments de la page du dessous.

Suggestion : 
* utiliser un tooltip pour les textes relativement courts
* utiliser une modale pour les contenus plus conséquents

**Comment by laem** [comment]
On avait pris la décision d'enlever les modales de l'expérience. Sur bureau, c'est plutôt OK, mais sur mobile, c'est compliqué de fonctionner avec des modales. L'alternative la plus simple étant d'afficher le texte d'aide en plein écran, d'en faire une page, avec une URL dédiée. 

Pour le tooltip, c'est encore pire sur mobile, en tout cas les tooltips volants. 

> ajoute un enfant dans le DOM, ce qui décale tous les éléments de la page du dessous.

Est-ce que c'est un problème ? Les deux suggestions consistent aussi à ajouter un élément dans le dom et à cacher le reste de la question (plutôt que de le décaler).

**Comment by bjlaa** [comment]
Depuis hier j'ai pris connaissance de l'importance du mobile-first pour le projet :) je retire cette suggestion, après avoir fait des essais avec NGC sur mobile ça fonctionne mieux qu'une modale ou un tooltip (complètement d'accord ces derniers sont horribles sur mobile)
