### ISSUE TITLE
Ajouter un outil de suivi des erreurs (Sentry)

### ISSUE THREAD

**Issue by bjlaa** [datagir/nosgestesclimat-site#941]
Nous n'utilisons pas à ma connaissance un outil de suivi d'erreurs. Cela me parait indispensable d'en faire usage notamment dans une optique de croissance du produit.
J'utilisais Sentry sur mon projet ([https://sentry.io/welcome/](https://sentry.io/welcome/)), ça fonctionne bien et c'est simple d'utilisation. C'est aussi très rapide à configurer.

**Comment by laem** [comment]
Quelles sont les implications en termes de vie privée ? 
Est-ce qu'on peut utiliser Sentry tout en gardant l'absence volontaire de bandeau cookies ? 

Si oui, alors carrément !

**Comment by bjlaa** [comment]
@laem https://help.sentry.io/account/legal/are-you-compliant-with-general-data-protection-regulation-gdpr/ ça a l'air d'être bon !

**Comment by bjlaa** [comment]
En profiter pour ajouter un `ErrorBoundary`
