### ISSUE TITLE
Faire un troisième audit des événements de parcours de simulation

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#961]
Pour ajouter une couche de confiance sur le fait que nos stats de funnel d'événement 

"1ère réponse au bilan" -> "Progress > 50%" -> "Progress > 90%" -> "A terminé le test" 

ne surestime pas le taux de succès.

**Comment by laem** [comment]
## Chiffres semaine du 18 avril 2023. 

Après la correction du bug de comptabilité de l'événement "1ère réponse au bilan", on est à 75% d'événements "A terminé la simulation" par rapport au nombre d'événements "1ère réponse au bilan". 
Soit pour 5 jours, 6 300 événements "simulation terminée" sur 8 450 "1ère réponse au bilan". 

Pour le rapport entre "1ère réponse" et "Progress > 50%" on est à 84%.
Pour le rapport entre "Progress > 50%" et "Progress > 90%", on est à 95%.
Pour le rapport entre "Progress > 90%" et "A terminé" on est à 93%.

(Sous réserve bien sûr que ces métriques soient fiables)

**Comment by laem** [comment]
Chiffres tirés des sondages enregistrés dans la base de donnée, qui confirment l'évaluation côté Matomo

![image](https://user-images.githubusercontent.com/1177762/232781971-cd735311-a5e2-4904-aa53-1ffe4541616c.png)

**Comment by laem** [comment]
- [ ] investiguer notamment : est-ce que notre code React/Redux marche bien ?

**Comment by bjlaa** [comment]
Résultats de mon audit :

* j'ai constaté que plusieurs trackers étaient lancés à des moments inopportuns ce qui fausse les évènement `50% de complétion`, `90% de complétion` et `simulation terminée`, il en résulte donc que les mesures faites sur ces trackers sont faussées ; 
* j'ai constaté qu'après l'ajout de Plausible, les valeurs trackées par Plausible et Matomo différaient largement, sur la journée du 24 avril par exemple :


![Image](https://user-images.githubusercontent.com/12382534/234528897-d2d614c8-3f8f-44cd-b999-435ba3dc08b9.png)



![Image](https://user-images.githubusercontent.com/12382534/234528921-70f86009-7853-46a9-9589-448e403a7ca5.png)

Je n'ai pas encore réussi à en déterminer la cause. Mis cela à part, le point important est que Plausible est trop limité pour le moment pour que l'on puisse en faire notre outil principal car il n'inclut pas la possibilité de créer des funnels et les recoupements de données sont quasiment inexistants. PLAUSIBLE OUT ! 🔥

**Comment by laem** [comment]
> j'ai constaté que plusieurs trackers étaient lancés à des moments inopportuns ce qui fausse les évènement 50% de complétion, 90% de complétion et simulation terminée, il en résulte donc que les mesures faites sur ces trackers sont faussées ;

Ah, tu as réussi à déterminer quand et pourquoi les trackers sont lancés plusieurs fois ? C'est un problème assez urgent à corriger du coup.

**Comment by laem** [comment]
> j'ai constaté qu'après l'ajout de Plausible, les valeurs trackées par Plausible et Matomo différaient largement, sur la journée du 24 avril par exemple :

Ah là clairement il y a un gros souci d'envoi d'événement côté plausible. 60 événements "NGC", c'est beaucoup trop peu par rapport aux visites.

**Comment by bjlaa** [comment]
## Test Posthog

Superbe outil, correspond mieux à ce que l'on recherche : interface moderne, funnels intégré dans les fonctionnalités, possibilité de se passer de bannière de cookie (à confirmer). Malheureusement la version cloud est beaucoup trop chère (estimation à 30k par an). À priori, c'est éliminatoire. Il reste cependant une solution proposée par Chaïb, héberger une instance Posthog sur Scalingo ce qui la rendrait gratuite (si on exclut les frais Scalingo, qui restent à déterminer). Recherches en cours à ce jour sur ce dernier point.

**Comment by bjlaa** [comment]
> Ah là clairement il y a un gros souci d'envoi d'événement côté plausible. 60 événements "NGC", c'est beaucoup trop peu par rapport aux visites.

Oui c'est bizarre, je soupçonne un bug côté Plausible.

**Comment by bjlaa** [comment]
https://matomo.org/faq/reports/user-id-privacy-considerations/ Okay sur Matomo, le fait de récupérer les id d'utilisateurs pour en dresser le profil, et lister leur parcours nécessite d'intégration d'une bannière de consentement. Donc à priori, sur Posthog on aurait le même problème !

**Comment by bjlaa** [comment]
# Protocole de test pour reproduire les évènements envoyés en doublon
* en local lancer `yarn dev`
* visiter `localhost:8080`, vider les données dans la console
* recharger la page
* cliquer sur Faire le test
* cliquer sur Passer le tutoriel
* rejoindre la première question, répondre et passer à la suivante pour arriver à cet état :
<img width="1440" alt="Capture d’écran 2023-04-27 à 16 25 51" src="https://user-images.githubusercontent.com/12382534/234893083-6de5c2bc-b52f-4cb0-9388-edc944300fc5.png">
* recharger la page : dans la console `['trackEvent', 'NGC', '1ère réponse au bilan']` s'affiche à nouveau
<img width="1438" alt="Capture d’écran 2023-04-27 à 16 27 01" src="https://user-images.githubusercontent.com/12382534/234893781-6e1613ad-df03-4514-8c4f-9fc03886a57d.png">
* appuyer sur la touche Esc jusqu'à ce que l'évènement 50% se lance dans la console :
<img width="1440" alt="Capture d’écran 2023-04-27 à 16 28 25" src="https://user-images.githubusercontent.com/12382534/234894542-51aef119-cfdd-4132-99e5-1d25fd6934ab.png">
* recharger la page, 1ere réponse et 50% sont à nouveau envoyés :
<img width="1440" alt="Capture d’écran 2023-04-27 à 16 29 56" src="https://user-images.githubusercontent.com/12382534/234894806-293067fb-11ac-4d05-85e4-344068eb7207.png">
* avancer avec Esc jusqu'à atteindre 90%, recharger la page, tous les évènements de progression sont re-déclenchés
<img width="1440" alt="Capture d’écran 2023-04-27 à 16 31 14" src="https://user-images.githubusercontent.com/12382534/234895221-494d3177-8283-4b54-8dad-ad8ce34e8f79.png">
* avancer avec Esc jusqu'à atteindre l'écran de fin du questionnaire :
<img width="1430" alt="Capture d’écran 2023-04-27 à 16 32 23" src="https://user-images.githubusercontent.com/12382534/234895524-5d034154-cc62-49fd-b754-601ca4c8ed7e.png">
* recharger la page, tous les évènements de progression sont envoyés à nouveau :
<img width="1440" alt="Capture d’écran 2023-04-27 à 16 33 09" src="https://user-images.githubusercontent.com/12382534/234895730-88ad8fd7-8802-412a-89e2-db0b0143aa7a.png">
* retourner sur localhost:8080 via la barre d'url pour simuler le cas d'un utilisateur qui reviendrait regarder/mettre à jour son test, cliquer sur Reprendre mon test, tous les évènements de progression sont encore une fois renvoyés :
<img width="1440" alt="Capture d’écran 2023-04-27 à 16 36 41" src="https://user-images.githubusercontent.com/12382534/234896766-e8d02ec1-f75b-4c55-a043-23aefe9b503f.png">

**Comment by laem** [comment]
OK je vois deux sujets séparés dans ton protocole. 

1) Notre système d'envoi d'événement avec ses marqueurs "déjà envoyés" considère qu'un F5 recrée une session et donc redéclenche les événements, c'est vrai. 

Mais c'est justement le boulot de Matomo et Plausible que de dédupliquer pour un visiteur unique ces événements. Sauf si j'ai pas compris quelque chose ? 

Ici dans les données pour aujourd'hui, on voit qu'il y a ~10% de différence entre les événements totaux et uniques pour "A terminé la simulation". 

![image](https://user-images.githubusercontent.com/1177762/234899700-0d7560aa-bc1d-44b9-9b5f-7345a7838e4f.png)

Les stats Plausible maintenant que tu as corrigé le bug :pray: les confirment. 

![image](https://user-images.githubusercontent.com/1177762/234903094-87d16e4b-3d8e-4b64-a0ee-056e1fa2e216.png)


Autre point : il y a fort à parier que peu de gens fassent F5. On peut très bien stocker les événements dans le localstorage, via quelques lignes de code en plus, c'est très rapide. 

2) (Dernière étape de ton protocole) Le fait qu'on ne stocke pas les marqueurs dans le localstorage fait qu'un utilisateur qui reviendrait sur NGC après quelques jours, semaines, ou mois se comporterait comme un F5 et redéclencherait en effet les événements, car il a bien effectivement complété le test, vu que ses données sont stockées dans le localstorage. 

Pour ce point là, il reste donc à déterminer pendant combien de temps Matomo considère que c'est le même utilisateur, donc finalement combien de temps le cookies reste. Car si l'utilisateur supprime ses cookies, on peut considérer qu'il supprime aussi son localstorage. Tu as investigué ce point ? 

Si je ne me trompe pas, ça correspond à `pk_id`, et la doc matomo dit qu'elles sont gardées pour 13 mois. https://fr.matomo.org/faq/general/faq_146. 
C'est aussi précisément ce que je constate dans mon navigateur sans ublock : 
![image](https://user-images.githubusercontent.com/1177762/234902381-538120e4-8705-4934-9d75-b3bf761e6f8b.png)

Ce qui voudrait dire que les utilisateurs qui reviennent sur NGC sont bien dédoublonnés dans la mesure des événements uniques. 

Du coup, si tu es d'accord avec mes deux points, ça nous laisse bredouille sur la recherche d'une faille dans le suivi du nombre d'événements ?

**Comment by bjlaa** [comment]
Pour résumer les actions entreprises suite à ma phase de recherche : 
* décision de garder Matomo en outil principal et Plausible en complément (à confirmer)
* centralisation de tous les évènements trackés dans un fichier
* envoi des évènements une seule fois, sauf cas particuliers (évènement pour suivre la session utilisateur par exemple) avec sauvegarde des évènements déjà envoyés dans le state persistant 
* centralisation de la logique de tracking dans un context React `MatomoContext`
