### ISSUE TITLE
Ergonomie réponses

### ISSUE THREAD

**Issue by publicodes** [datagir/nosgestesclimat-site#97]
Il n'est pas particulièrement agréable de répondre au questionnaire en l'état. 
Ces petits détails qui font la différence :

- le choix du chauffage posé sous la forme d'une série de questions oui/non, alors qu'une seule question avec les options gaz/fioul/électrique suffit

- grouper les questions par trois ou quatre permettrait de ne pas cliquer sur « suivant » à chaque fois

- quand on revient en arrière, il est actuellement obligatoire de répondre de nouveau pour pouvoir cliquer sur suivant, même si on ne change pas sa réponse. C'est un peu contre-intuitif.

**Comment by laem** [comment]
Je ferme en l'absence d'une discussion sur la base de ma réponse.
