### ISSUE TITLE
Expliquer s'il faut compter les déplacements domicile travail et les dplcmts pro

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#99]
>  2/ pour toutes les questions de la rubrique transport, ce n'est pas clair pour moi si je dois compléter en prenant en compte mes déplacements professionnels ou pas ?

Je pense qu'il va falloir expliquer ça sur l'écran "transport" (un texte associé à l'icône), ou comme une question rhétorique (étape du simulateur où l'on ne peut répondre que "D'accord").

**Comment by Clemog** [comment]
C'est préciser dans la bulle info mais plus de pédagogie sur le sujet est primordial (#539)
